objects/Account.object
<CustomObject>
    <fields>
        <fullName>Facility_Classification__c</fullName>
        <label>Facility Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Type__c</fullName>
        <label>Facility Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Type_c</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OneKey_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OneKey Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>NCT_Number__c</fullName>
        <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
        <label>NCT Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Override_Recruitment_Status__c</fullName>
        <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
        <label>Override Recruitment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actively Enrolling</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Enrollment Closed</fullName>
                </value>
                <value>
                    <fullName>No_Longer_Enrolling</fullName>
                    <label>No Longer Enrolling</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <description>QI assigned unique ID for a study</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
        <label>Protocol ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>Title of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Title</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Doctorate</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OneKey_ID__c</fullName>
        <description>QI One Key ID Number. If an existing HCP, then value will come from ACOE.  If self-enroll, OneKey API to be called to determine if HCP exists.  Otherwise, this will get updated based on the Acknowledgement ID from OneKey.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>OneKey ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Reimbursement_Currency__c</fullName>
        <label>Preferred Reimbursement Currency</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Preferred_Reimbursement_Currency</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Degree__c</fullName>
        <label>Degree</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Doctorate</fullName>
                </value>
                <value>
                    <fullName>Doctors Of Osteopathy</fullName>
                </value>
                <value>
                    <fullName>Medical Doctors</fullName>
                </value>
                <value>
                    <fullName>Nurse</fullName>
                </value>
                <value>
                    <fullName>Office Manager</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Classification__c</fullName>
        <label>Facility Classification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Classification</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Facility_Type__c</fullName>
        <label>Facility Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Facility_Type_c</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCP_Referral_Source__c</fullName>
        <label>HCP Referral Source</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HCP_Referral_Source_c</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>OneKey_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>OneKey Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OneKey_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>OneKey ID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <formula>Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Study Code Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

objects/Material_Sent__c.object
<CustomObject>
    <fields>
        <fullName>Material_Sent__c</fullName>
        <label>Material Sent</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Material_Sent</valueSetName>
        </valueSet>
    </fields>
    <label>Material Sent</label>
    <nameField>
        <label>Material Sent ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials Sent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Clinical Trial Profile&apos;s Protocol Id</inlineHelpText>
        <label>Protocol ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Study Site Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_LeadConversion.cls
/**
 * Created by Kryvolap on 23.10.2018.
 */
@isTest
private class Test_LeadConversion {
    static Account piAccount;
    static Account studySiteAccount;

    static Contact piContact;

    static User piUser;

    static Clinical_Trial_Profile__c study;
    static Study_Site__c studySite;

    static Terms_And_Conditions__c studyTC;

    static Lead testLead;
    static National_ID__c natId;
    static Material_Sent__c material;
    static void init() {

        studyTC = new Terms_And_Conditions__c();
        insert studyTC;

        piAccount = new Account(
                Name = 'PI Account'
        );
        insert piAccount;

        studySiteAccount = new Account(
                Name = 'Study Site Account'
        );
        insert studySiteAccount;

        piContact = new Contact(
                FirstName = 'PI',
                LastName = 'PI',
                Email = 'pi@emil.com',
                AccountId = piAccount.Id
        );
        insert piContact;


        study = new Clinical_Trial_Profile__c(
                Protocol_ID__c = 'tt123456789',
                Override_Recruitment_Status__c = 'Actively Enrolling',
                NCT_Number__c = 'NCT00000001',
                Link_to_Pre_screening__c = 'some link',
                Terms_And_Conditions_ID__c = studyTC.Id,
                Study_Title__c = 'Some Title',
                Study_Code_Name__c = 'Some Code Name'

        );
        insert study;

        studySite = new Study_Site__c(

                Principal_Investigator__c = piContact.Id,
                Clinical_Trial_Profile__c = study.Id,
                Override_PI_Referral_Status__c = StudySiteService.PI_S_INVITATION_SENT,
                Study_Site_Number__c = '1234567',
                Site__c = studySiteAccount.Id,
                Is_Virtual_Study_Site__c = true
        );
        insert studySite;
        studySite.Override_PI_Referral_Status__c = StudySiteService.PI_S_ACCEPTED;
        update studySite;


        testLead = new Lead();
        testLead.FirstName = 'Test';
        testLead.LastName = 'Lead';
        testLead.Email = 'test@test.com';
        testLead.Status = 'New';
        testLead.Company = 'Test Lead Comp';
        testLead.Tax_ID__c = '111111';
        testLead.Degree__c = 'Doctorate';
        testLead.Facility_Type__c = 'Medical Group';
        testLead.Facility_Classification__c = 'Hospital';
        testLead.HCP_Referral_Source__c = 'ACOE Data';
        //testLead.Lead_CTE__c = 'Some text';
        testLead.OneKey_Code__c = '1234567';
        testLead.OneKey_ID__c = '1234567';
        testLead.Preferred_Reimbursement_Currency__c = 'USD';
        testLead.Previous_Trial_Experience__c = 'Yes';
        testLead.Specialty__c = 'Cardiovascular Disease';
        testLead.Contact_Method_Preference__c='Call';
        testLead.POC_First_Name__c = 'POC';
        testLead.POC_Last_Name__c = 'Test';
        testLead.POC_Email__c = 'POC@test.com';
        testLead.POC_Type__c = 'Office Manager';
        testLead.POC_Type_Description__c = '';
        testLead.POC_Phone__c = '444333222';
        testLead.Protocol_Number__c='tt123456789';
        testLead.Study_Site_Number__c='1234567';
        insert testLead;

        natId = new National_ID__c();
        natId.Lead__c = testLead.Id;
        natId.Name = '1234567890';
        natId.Country_Code__c = 'US';
        insert natId;

        material = new Material_Sent__c();
        material.Material_Sent__c = 'Poster';
        material.Lead__c = testLead.Id;
        insert material;

    }
    @isTest
    static void mainConversionTest() {
        init();
        Test.startTest();
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(testLead.Id);
        lc.setDoNotCreateOpportunity(true);
        lc.setConvertedStatus('Qualified');
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        Test.stopTest();
    }

}