objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <description>QI assigned unique ID for a study</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
        <label>Protocol ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Key__c</fullName>
        <description>STDY_SITE_KEY + INVSTGR_KEY</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>STDY_SITE_KEY + INVSTGR_KEY</inlineHelpText>
        <label>Primary Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Key_ePR__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Primary Key ePR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Clinical Trial Profile&apos;s Protocol Id</inlineHelpText>
        <label>Protocol ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Study Site Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Batch_UpdateStudySitePrimaryKey.cls
/**
 * Created by Kryvolap on 23.01.2019.
 */


global with sharing class Batch_UpdateStudySitePrimaryKey implements Database.Batchable<sObject> {


    global Batch_UpdateStudySitePrimaryKey() {
    }


    global Database.querylocator start(Database.BatchableContext BC) {
        String strQuery = 'SELECT Id, Clinical_Trial_Profile__r.Protocol_ID__c, Site__r.BillingCountryCode, Study_Site_Number__c, Primary_Key__c, Primary_Key_ePR__c FROM Study_Site__c';
        return Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<Study_Site__c> scope) {
        for (Study_Site__c study : scope) {
            study.Primary_Key_ePR__c = study.Clinical_Trial_Profile__r.Protocol_ID__c + '_' + study.Site__r.BillingCountryCode + '_' + study.Study_Site_Number__c;
        }
        update scope;
    }


    global void finish(Database.BatchableContext BC) {
    }

}