objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Override_Recruitment_Status__c</fullName>
        <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
        <label>Override Recruitment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actively Enrolling</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Enrollment Closed</fullName>
                </value>
                <value>
                    <fullName>No_Longer_Enrolling</fullName>
                    <label>No Longer Enrolling</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>HCP Status per clinical trial by PI</description>
        <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
        <label>HCP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>On Hold (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending Orientation</fullName>
                </value>
                <value>
                    <fullName>Declined (Approval)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Approval)</fullName>
                </value>
                <value>
                    <fullName>Declined (Activation)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Activation)</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Activated (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Admin)</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudyListViewController.cls
/**
 * Created by D.Yasinskyi on 14.02.2018
 */
public without sharing class StudyListViewController {
    
    class StudyDetailItem {
        Clinical_Trial_Profile__c trial;
        List<StudyActions.Action> studyActions;
        String studyStatus;
        Study_Site__c ss;
        HCP_Enrollment__c hcpe;
        List<StudyTotalPassed> statistics = new List<StudyTotalPassed>();
        String trialRecruitmentStatusLabel;
    }
    
    class StudiesGroup{
        String name;
        List<StudyDetailItem> studies = new List<StudyDetailItem>();
        
        StudiesGroup(String name){
            this.name = name;
        }
    }
    
    class InitData{
        List<StudyDetailItem> trialsNoLongerRecruiting = new List<StudyDetailItem>();
        List<StudiesGroup> currentlyRecruitingTrials = new List<StudiesGroup>();
        Map<String, PEStatusState> peStatusStateMap = PEStatusState.STATUSES_MAP;
        List<String> peStatusesPathList = PEStatusState.STATUS_STEPS_LIST;
        List<Participant_Enrollment__c> peList = new List<Participant_Enrollment__c>();
        List<Participant_Enrollment__c> peListNoLongerRecr = new List<Participant_Enrollment__c>();
    }
    
    @AuraEnabled
    public static String getStudyTrialList(String userMode) {
        try{
            InitData initData = new InitData();
            List<StudyDetailItem> studies;
            if (userMode == CommunityService.USER_MODE_HCP) {
                studies = getStudiesForHCP();
                groupTrials(initData, studies, userMode);
            } else if (userMode == CommunityService.USER_MODE_PI) {
                studies = getStudiesForPI();
                groupTrials(initData, studies, userMode);
                loadStatistics(studies);
            } else if (userMode == CommunityService.USER_MODE_PARTICIPANT) {
                Participant_Enrollment__c[] peList = ParticipantEnrollmentService.getParticipantEnrollmentsForParticipant();
                for(Participant_Enrollment__c pe : peList){
                    if(pe.Study_Site__r.Clinical_Trial_Profile__r.Override_Recruitment_Status__c != TrialService.STATUS_ACTIVELY_ENROLLING){
                        initData.peListNoLongerRecr.add(pe);
                    }else{
                        initData.peList.add(pe);
                    }
                }
            }
            return JSON.serialize(initData);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    public static List<StudyDetailItem> getStudiesForHCP() {
        // prepare map trialId -> HCPEnrollment:
        Map<Id, HCP_Enrollment__c> trialHCPEnrollmentMap = new Map<Id, HCP_Enrollment__c>();
        for(HCP_Enrollment__c enrollment : HCPEnrollmentService.getHCPEnrollmentsForHCP()){
            trialHCPEnrollmentMap.put(enrollment.Study_Site__r.Clinical_Trial_Profile__c, enrollment);
        }
        // get trials with fields and TC:
        List<Clinical_Trial_Profile__c> trials = SudyTrialService.getTrials(trialHCPEnrollmentMap.keySet());
        Map<Id, Boolean> termsAcceptedMap = TermsAndConditions.getTrialsAcceptanceMap(trials);
        //prepare list of studies:
        List<StudyDetailItem> studies = new List<StudyDetailItem>();
        for (Clinical_Trial_Profile__c trial : trials) {
            HCP_Enrollment__c hcpe = trialHCPEnrollmentMap.get(trial.Id);
            StudyDetailItem studyDetailItem = new StudyDetailItem();
            studyDetailItem.hcpe = hcpe;
            studyDetailItem.trial = trial;
            studyDetailItem.studyStatus = hcpe.Status__c;
            studyDetailItem.studyActions = new StudyActionsHCP(hcpe).studyListViewItemActions;
            studyDetailItem.trialRecruitmentStatusLabel = TranslateHelper.getPickListLabel(Clinical_Trial_Profile__c.Override_Recruitment_Status__c, trial.Override_Recruitment_Status__c);
            studies.add(studyDetailItem);
        }
        return studies;
    }

    public static List<StudyDetailItem> getStudiesForPI() {
        // prepare map trialId -> StudySite
        Map<Id, Study_Site__c> trialStudySiteMap = new Map<Id, Study_Site__c>();
        for (Study_Site__c studySite : StudySiteService.getStudySitesForPI()) {
            trialStudySiteMap.put(studySite.Clinical_Trial_Profile__c, studySite);
        }
        // get trials and TC:
        List<Clinical_Trial_Profile__c> trials = SudyTrialService.getTrials(trialStudySiteMap.keySet());
        Map<Id, Boolean> termsAcceptedMap;
        termsAcceptedMap = TermsAndConditions.getTrialsAcceptanceMap(trials);
        // prepare result list:
        List<StudyDetailItem> studies = new List<StudyDetailItem>();
        for (Clinical_Trial_Profile__c trial : trials) {
            Study_Site__c ss = trialStudySiteMap.get(trial.Id);
            StudyDetailItem studyDetailItem = new StudyDetailItem();
            studyDetailItem.trial = trial;
            studyDetailItem.studyStatus = ss.Override_PI_Referral_Status__c;
            studyDetailItem.ss = ss;

            studyDetailItem.studyActions = new StudyActionsPI(trialStudySiteMap.get(trial.Id)).studyListViewItemActions;
            studyDetailItem.trialRecruitmentStatusLabel = TranslateHelper.getPickListLabel(Clinical_Trial_Profile__c.Override_Recruitment_Status__c, trial.Override_Recruitment_Status__c);
            studies.add(studyDetailItem);
        }
        return studies;
    }
    
    public static void groupTrials(InitData initData, List<StudyDetailItem> allStudies, String userMode){
        StudiesGroup activated = new StudiesGroup(userMode == CommunityService.USER_MODE_PI ? Label.SGT_Accepted_and_active : Label.SGT_Activated);
        StudiesGroup pendingStudySiteAction = new StudiesGroup(Label.SGT_Pending_Study_Site_s_Action);
        StudiesGroup onHold = new StudiesGroup(Label.SGT_On_hold);
        StudiesGroup pendingYourAction = new StudiesGroup(Label.SGT_Pending_Your_Action);
        StudiesGroup declined = new StudiesGroup(Label.SGT_Declined_Acceptance);
        StudiesGroup declinedOther = new StudiesGroup(Label.SGT_Declined_by_Others);
        StudiesGroup deactivated = new StudiesGroup(Label.SGT_Deactivated);
        for(StudyDetailItem item : allStudies){
            TranslateHelper.translate(item.trial);
            if(item.trial.Override_Recruitment_Status__c != TrialService.STATUS_ACTIVELY_ENROLLING){
                initData.trialsNoLongerRecruiting.add(item);
            }else if (item.studyStatus.startsWith('Activated') || item.studyStatus.startsWith('Accepted')){
                activated.studies.add(item);
            }else if(item.studyStatus == StudySiteService.PI_S_INVITATION_SENT){
                pendingYourAction.studies.add(item);
            }else if(item.studyStatus.contains('Pending')){
                pendingStudySiteAction.studies.add(item);
            }else if(item.studyStatus.startsWith('On Hold')){
                onHold.studies.add(item);
            }else if(item.studyStatus == 'Declined (Acceptance)' || item.studyStatus == 'Non-Responsive (Admin)'){
                declined.studies.add(item);
            }else if(item.studyStatus.contains('Declined')){
                declinedOther.studies.add(item);
            }else if(item.studyStatus == 'Deactivated (Admin)'){
                deactivated.studies.add(item);
            }
        }
        if(activated.studies.size() > 0) initData.currentlyRecruitingTrials.add(activated);
        if(pendingYourAction.studies.size() > 0) initData.currentlyRecruitingTrials.add(pendingYourAction);
        if(pendingStudySiteAction.studies.size() > 0) initData.currentlyRecruitingTrials.add(pendingStudySiteAction);
        if(onHold.studies.size() > 0) initData.currentlyRecruitingTrials.add(onHold);
        if(declined.studies.size() > 0) initData.currentlyRecruitingTrials.add(declined);
        if(declinedOther.studies.size() > 0) initData.currentlyRecruitingTrials.add(declinedOther);
        if(deactivated.studies.size() > 0) initData.currentlyRecruitingTrials.add(deactivated);
    }
    
    
    public static void loadStatistics(List<StudyDetailItem> studies){
        Map<Id, Integer> referredCountMap = ParticipantEnrollmentService.getReferredByTrial();
        String allReviewedFilter = ' AND Participant_Status__c IN (\'' + String.join(new List<String>(PEStatusState.ALL_USED_STATUSES_WITH_REFERRING), '\',\'') + '\') ';
        Map<Id, Integer> allCountMap = ParticipantEnrollmentService.getPECountMapByTrialsForPI(allReviewedFilter);
        for(StudyDetailItem item : studies){
            item.statistics.add(new StudyTotalPassed('all',
                    allCountMap.get(item.trial.Id),
                    referredCountMap.get(item.trial.Id)
            ));
        }
    }
    
}