objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>NCT_Number__c</fullName>
        <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
        <label>NCT Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Suppress_Participant_Emails__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, no emails will be sent to participants for this study.</inlineHelpText>
        <label>Suppress Participant Emails</label>
        <type>Checkbox</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>userCommunityMode__c</fullName>
        <description>Current view point for Community</description>
        <label>User Community Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <formula>Study_Site__r.Is_Virtual_Study_Site__c</formula>
        <label>Is Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsCountry_NOT_Eligible_for_Emails__c</fullName>
        <formula>NOT(Mailing_Country_Code__c=&apos;US&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Country NOT Eligible for Emails</label>
        <type>Checkbox</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact_HCPEnroll__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Testing</description>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Enrollments (HCP Contact)</relationshipLabel>
        <relationshipName>Participant_Enrollments2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; HCP__r.HCP_Contact__c ,HCP__r.HCP_Contact__r.FirstName&amp;&quot; &quot;&amp;  HCP__r.HCP_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HCP Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <formula>Study_Site__r.Is_Virtual_Study_Site__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PI_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>PI Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Enrollments (PI)</relationshipLabel>
        <relationshipName>Participant_Profile2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Enrollments (Participant Contact)</relationshipLabel>
        <relationshipName>PE_Participant_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant_Key__c</fullName>
        <description>Participant Key = Participant number + NCT number</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Participant Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referred_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Date Potential Participant referred to a Site / PI</inlineHelpText>
        <label>Referred Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PI_Contact__c</fullName>
        <formula>HYPERLINK( &quot;/&quot;&amp;Principal_Investigator__c , Principal_Investigator__r.FirstName&amp;&quot; &quot; &amp;Principal_Investigator__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PI Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suppress_Participant_Emails__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, no emails will be sent to participants for this study site.</inlineHelpText>
        <label>Suppress Participant Emails</label>
        <type>Checkbox</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ParticipantEnrollmentTriggerHandler.cls
/**
 * Created by D.Yasinskyi on 26.04.2018
 * Refactored by L.Bartenev
 */

public without sharing class ParticipantEnrollmentTriggerHandler {
    
    private Map<Id, Participant_Enrollment__c> oldMap;
    private Map<Id, Participant_Enrollment__c> newMap;
    private List<Participant_Enrollment__c> oldList;
    private List<Participant_Enrollment__c> newList;
    
    private Map<Id, Study_Site__c> ssMap;
    private Map<Id, HCP_Enrollment__c> hcpeMap;
    private Map<Id, Participant__c> participantMap;
    
    public ParticipantEnrollmentTriggerHandler(){
        oldList = (List<Participant_Enrollment__c>)Trigger.old;
        newList= (List<Participant_Enrollment__c>)Trigger.new;
    
        List<Id> ssIds = new List<Id>();
        List<Id> hcpeIds = new List<Id>();
        List<Id> participantIds = new List<Id>();
        for(Participant_Enrollment__c pe : newList){
            if(pe.Study_Site__c != null) ssIds.add(pe.Study_Site__c);
            if(pe.HCP__c != null) hcpeIds.add(pe.HCP__c);
            if(pe.Participant__c != null) participantIds.add(pe.Participant__c);
        }
        ssMap = new Map<Id, Study_Site__c>([
                SELECT Id, Principal_Investigator__c,
                        Suppress_Participant_Emails__c,
                        Clinical_Trial_Profile__c,
                        Clinical_Trial_Profile__r.Suppress_Participant_Emails__c,
                        Clinical_Trial_Profile__r.NCT_Number__c
                FROM Study_Site__c
                WHERE Id IN: ssIds
        ]);
        hcpeMap = new Map<Id, HCP_Enrollment__c>([
                SELECT Id, HCP_Contact__c
                FROM HCP_Enrollment__c
                WHERE Id IN: hcpeIds
        ]);
        participantMap = new Map<Id, Participant__c>([
                SELECT Id, Contact__c, Name,
                        IsCountry_NOT_Eligible_for_Emails__c
                FROM Participant__c
                WHERE Id IN: participantIds
        ]);
    
        if(Trigger.isUpdate){
            oldMap = new Map<Id, Participant_Enrollment__c>(oldList);
            newMap = new Map<Id, Participant_Enrollment__c>(newList);
        }
    }
    
    public void handle(){
        if(Trigger.isUpdate || Trigger.isInsert){
            if(Trigger.isBefore){
                prepareAdditionalFields();
            }
            if(Trigger.isAfter){
                createUsersOrSendNotifications();
            }
        }
    }
    
    private void prepareAdditionalFields(){
        for(Participant_Enrollment__c pe : newList){
            String nctNumber;
            String participantName;
            if(pe.Study_Site__c != null){
                Study_Site__c ss = ssMap.get(pe.Study_Site__c);
                if(ss != null) {
                    pe.PI_Contact__c = ss.Principal_Investigator__c;
                    pe.Clinical_Trial_Profile__c = ss.Clinical_Trial_Profile__c;
                    nctNumber = ss.Clinical_Trial_Profile__r.NCT_Number__c;
                }
            }
            if(pe.HCP__c != null){
                HCP_Enrollment__c hcpe = hcpeMap.get(pe.HCP__c);
                if(hcpe != null) pe.HCP_Contact_HCPEnroll__c = hcpe.HCP_Contact__c;
            }
            if(pe.Participant__c != null){
                Participant__c participant = participantMap.get(pe.Participant__c);
                if(participant != null) {
                    pe.Participant_Contact__c = participant.Contact__c;
                    participantName = participant.Name;
                }
            }
            //populate Participant Code
            if(nctNumber != null && participantName != null){
                pe.Participant_Key__c = participantName + ' ' + nctNumber;
            }
            //populate referred date
            if(pe.Participant_Status__c == PEStatusState.PE_STATUS_REFERRAL_SENT_TO_PI){
                if(Trigger.isInsert || (Trigger.isUpdate && oldMap.get(pe.Id).Participant_Status__c != pe.Participant_Status__c)){
                    pe.Referred_Date__c = Date.today();
                }
            }
        }
    }
    
    private void createUsersOrSendNotifications() {
        Map<Id, Id> toCreateUser = new Map<Id, Id>();
        Map<Id, String> notificationMap = new Map<Id, String>();
        Map<Id, String> notificationMapEmptyHCP = new Map<Id, String>();
        Map<Id, String> toSendNotificationMap = new Map<Id, String>();
        List<Contact> contactsForChangeMode = new List<Contact>();
        
        //get users if exist
        Map<Id, User> usersByContactId = new Map<Id, User>();
        Set<Id> participantContactIds = new Set<Id>();
        for(Participant_Enrollment__c pe : newList) {
            Participant__c participant = participantMap.get(pe.Participant__c);
            if(participant != null && participant.Contact__c != null) participantContactIds.add(participant.Contact__c);
        }
        for (User usr : CommunityService.getCommunityUsersByContactIds(participantContactIds)) usersByContactId.put(usr.ContactId, usr);
        
        //process PE items:
        for(Participant_Enrollment__c newPE : newList){
            Study_Site__c ss = ssMap.get(newPE.Study_Site__c);
            HCP_Enrollment__c hcpe = hcpeMap.get(newPE.HCP__c);
            Participant__c participant = participantMap.get(newPE.Participant__c);
            User participantUser;
            if(participant != null && participant.Contact__c != null) participantUser = usersByContactId.get(participant.Contact__c);
            Boolean updateCriteria = true;
            if(oldMap != null){
                Participant_Enrollment__c oldPE = oldMap.get(newPE.Id);
                updateCriteria = oldPE.Participant_Status__c != newPE.Participant_Status__c ||
                        oldPE.Participant__c != newPE.Participant__c || participantUser == null;
                System.debug('OLD STATUS: ' +  oldPE.Participant_Status__c);
                System.debug('NEW STATUS: ' +  newPE.Participant_Status__c);
                System.debug('OLD PART ID: ' +  oldPE.Participant__c);
                System.debug('NEW PART ID: ' +  newPE.Participant__c);
                System.debug('PART USER: ' +  participantUser);
            }
            System.debug('UPDATE CRITERIA: ' + updateCriteria);
            if(!updateCriteria) continue;
            Boolean filterCriteria =
                            newPE.Participant_Status__c == PEStatusState.PE_STATUS_REFERRAL_SENT_TO_PI &&
                            newPE.Participant__c != null &&
                            !newPE.Is_Virtual_Study_Site__c &&
                            ss != null &&
                            ss.Clinical_Trial_Profile__c != null &&
                            !ss.Suppress_Participant_Emails__c &&
                            !ss.Clinical_Trial_Profile__r.Suppress_Participant_Emails__c &&
                            participant != null &&
                            !participant.IsCountry_NOT_Eligible_for_Emails__c &&
                            participant.Contact__c != null;
            System.debug('FILTER CRITERIA: ' + filterCriteria);
            if(filterCriteria){
                if(participantUser == null){
                    System.debug('CREATE USER');
                    Id hcpContact;
                    if(hcpe != null) hcpContact = hcpe.HCP_Contact__c;
                    toCreateUser.put(participant.Contact__c, hcpContact);
                }else{
                    System.debug('NOTIFY USER');
                    if(hcpe != null){
                        notificationMap.put(newPE.Id, participant.Contact__c);
                    }else{
                        notificationMapEmptyHCP.put(newPE.Id, participant.Contact__c);
                    }
                }
                contactsForChangeMode.add(new Contact(
                        Id = participant.Contact__c,
                        userCommunityMode__c = CommunityService.USER_MODE_PARTICIPANT
                ));
            }
        }
    
        if(toCreateUser.size() > 0) CommunityService.createParticipantUsers(toCreateUser);
        if(notificationMap.size() > 0) SendEmailTemplate.sendEmailNotification(SendEmailTemplate.EMAIL_TEMPLATE_PATIENT1_NEW, notificationMap);
        if(notificationMapEmptyHCP.size() > 0) SendEmailTemplate.sendEmailNotification(SendEmailTemplate.EMAIL_TEMPLATE_PATIENT2_NEW, notificationMapEmptyHCP);
        update contactsForChangeMode;
    }
    
}