objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Study_Site__r.Site__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Participant&apos;s First Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s First Name</inlineHelpText>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Participant&apos;s Last Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s Last Name</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Non_Referral_Reason__c</fullName>
        <label>Non- Referral Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Had Discussion, Not Interested</fullName>
                </value>
                <value>
                    <fullName>No Longer Interested</fullName>
                </value>
                <value>
                    <fullName>Failed Pre-Eligibility Screening</fullName>
                </value>
                <value>
                    <fullName>Did not pass chart review</fullName>
                    <isActive>false</isActive>
                    <label>Did not pass chart review</label>
                </value>
                <value>
                    <fullName>Did not pass pre-eligibility</fullName>
                    <isActive>false</isActive>
                    <label>Did not pass pre-eligibility</label>
                </value>
                <value>
                    <fullName>No suitable site</fullName>
                    <isActive>false</isActive>
                    <label>No suitable site</label>
                </value>
                <value>
                    <fullName>Not interested</fullName>
                    <isActive>false</isActive>
                    <label>Not interested</label>
                </value>
                <value>
                    <fullName>Other</fullName>
                    <isActive>false</isActive>
                    <label>Other</label>
                </value>
                <value>
                    <fullName>Stopped at agreement for T&amp;C / Refer</fullName>
                    <isActive>false</isActive>
                    <label>Stopped at agreement for T&amp;C / Refer</label>
                </value>
                <value>
                    <fullName>Unable to consult</fullName>
                    <isActive>false</isActive>
                    <label>Unable to consult</label>
                </value>
                <value>
                    <fullName>Unable to contact</fullName>
                    <isActive>false</isActive>
                    <label>Unable to contact</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Participant Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Surname__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Participant Surname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_screening_Status__c</fullName>
        <label>Pre-screening Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Referral_Completed_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral Completed by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Enrollments (Pre-Screening  Completed by)</relationshipLabel>
        <relationshipName>Participant_Enrollments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Study_Site__r.Site__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReferringRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class ReferringRemote {


    public class InitData{
        public Clinical_Trial_Profile__c trial;
        public HCP_Enrollment__c hcpEnrollment;
        public Participant_Enrollment__c participantEnrollment;
        public List<Participant_Enrollment__c> pendingPEnrollments;
        public List<AccountWrapper> studies;
        public Map<String, StudyActions.Action> actions;
        public List<LabelValueItem> countries;
        public Map<String, List<LabelValueItem>> statesByCountryMap;
    }

    public class AccountWrapper{
        public Account clinic;
        public String name;
        public String addrStreet;
        public String addrCity;
    }

    @AuraEnabled
    public static String getInitData(Id trialId, Id peId, String userMode){
        try{
            InitData initData = new InitData();
            initData.trial = TrialService.getTrial(trialId);
            //localize pes
            if(initData.trial.Link_to_Pre_screening__c != null){
                initData.trial.Link_to_Pre_screening__c = CommunityFacadeRemote.getLocalizedURL(initData.trial.Link_to_Pre_screening__c);
            }
            initData.hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
            new StudyActionsHCP(initData.hcpEnrollment).checkAction(StudyActions.ACT_REFER_TO_THIS_STUDY);
            initData.actions = new StudyActionsHCP(initData.hcpEnrollment).actions;
            if(peId != null) {
                initData.participantEnrollment = ParticipantEnrollmentService.getParticipantEnrollment(peId, userMode);
            }else if (initData.trial.Link_to_Medical_Record_Review__c == null){
                initData.participantEnrollment = ParticipantEnrollmentService.createParticipantEnrollment(initData.trial, initData.hcpEnrollment, null);
            }
            if(initData.trial.Link_to_Medical_Record_Review__c != null) {
                initData.pendingPEnrollments = ParticipantEnrollmentService.getPendingParticipantEnrollments(initData.hcpEnrollment.Id);
            }
            initData.studies = new List<AccountWrapper>();
            Account site = [
                    SELECT Id, Name, BillingStreet, BillingState, BillingPostalCode, BillingCity, Phone,
                            BillingLongitude, BillingLatitude
                    FROM Account
                    WHERE Id =: initData.hcpEnrollment.Study_Site__r.Site__c
            ];
            AccountWrapper aw = new AccountWrapper();
            aw.name = initData.hcpEnrollment.Study_Site__r.Name;
            aw.addrStreet = site.BillingStreet;
            aw.addrCity = getCityString(site);
            aw.clinic = site;
            initData.studies.add(aw);
            initData.countries = CountryStateUtil.getCountries();
            initData.statesByCountryMap = CountryStateUtil.getStatesByCountryMap();
            return JSON.serialize(initData);
        }catch (Exception e){
            System.debug('ERROR: ' + e.getMessage() + '\n' + e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    @AuraEnabled
    public static void saveParticipant(Id trialId, String pEnrollmentJSON, String participantJSON){
        Participant__c participant = (Participant__c)JSON.deserialize(participantJSON, Participant__c.class);
        HCP_Enrollment__c hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
        Participant_Enrollment__c participantEnrollment = (Participant_Enrollment__c)JSON.deserialize(pEnrollmentJSON, Participant_Enrollment__c.class);
        participantEnrollment.Participant_Status__c = ParticipantEnrollmentService.PART_STATUS_REFERRAL_SENT_TO_PI;
        if(participantEnrollment.Pre_screening_Status__c == ParticipantEnrollmentService.PES_STATUS_PENDING){
            participantEnrollment.Pre_screening_Status__c = ParticipantEnrollmentService.PES_STATUS_PASS;
        }

        Database.SaveResult saveResult = Database.insert(participant, false);
        if (!saveResult.isSuccess()) {
            System.debug('PARTICIPANT INSERT ERROR');
            for (Database.Error error : saveResult.getErrors()) {
                if (error instanceof Database.DuplicateError) {
                    Database.DuplicateError duplicateError = (Database.DuplicateError) error;
                    Datacloud.DuplicateResult duplicateResult = duplicateError.getDuplicateResult();
                    List<SObject> duplicateRecords = new List<SObject>();
                    Datacloud.MatchResult[] matchResults = duplicateResult.getMatchResults();
                    Datacloud.MatchResult matchResult = matchResults[0];
                    Datacloud.MatchRecord[] matchRecords = matchResult.getMatchRecords();
                    for (Datacloud.MatchRecord matchRecord : matchRecords) {
                        participant = (Participant__c) matchRecord.getRecord();
                        System.debug('FOUND PART DUPLICATE: ' + participant);
                        break;
                    }
                }else{
                    throw new AuraHandledException(error.getMessage());
                }
            }
        }

        if(participant.Id != null){
            participantEnrollment.Participant__c = participant.Id;
            participantEnrollment.HCP__c = hcpEnrollment.Id;
            participantEnrollment.Referral_Completed_by__c = CommunityService.getUserContact().Id;
            if(participantEnrollment.Participant_Name__c == null) participantEnrollment.Participant_Name__c = participant.First_Name__c;
            if(participantEnrollment.Participant_Surname__c == null) participantEnrollment.Participant_Surname__c = participant.Last_Name__c;
            try{
                upsert participantEnrollment;
            }catch (Exception e){
                String errorMsg = e.getMessage();
                if(errorMsg.contains('DUPLICATE')) {
                    errorMsg = 'This patient has already been referred to this study. A patient can only be referred to one trial at a time';
                }
                System.debug('ERROR: ' + errorMsg);
                throw new AuraHandledException(errorMsg);
            }
        }else{
            throw new AuraHandledException('Can not create participant');
        }
    }

    @AuraEnabled
    public static void setfailedReferral(String peJSON, String reason){
        try {
            Participant_Enrollment__c pe = (Participant_Enrollment__c)JSON.deserialize(peJSON, Participant_Enrollment__c.class);
            pe.Participant_Status__c = ParticipantEnrollmentService.PART_STATUS_FAILED_REFERRAL;
            if(pe.Pre_screening_Status__c != ParticipantEnrollmentService.PES_STATUS_NOT_REQUIRED)
                pe.Pre_screening_Status__c = ParticipantEnrollmentService.PES_STATUS_FAIL;
            pe.Non_Referral_Reason__c = reason;
            if(reason == ParticipantEnrollmentService.NON_REF_REASON_STATUS_FAILED_PE_SCREENING){
                pe.Pre_screening_Status__c = ParticipantEnrollmentService.PES_STATUS_FAIL;
            }
            upsert pe;
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    private static String getCityString(Account acc){
        List<String> addressList = new List<String>();
        if(acc.BillingCity != null) addressList.add(acc.BillingCity);
        if(acc.BillingState != null) addressList.add(acc.BillingState);
        if(acc.BillingPostalCode != null) addressList.add(acc.BillingPostalCode);
        return String.join(addressList, ', ');
    }
    
    public static final Map<String, List<String>> STATES_MAP = FieldDescribeUtil.getDependentOptionsImpl(
            User.CountryCode,
            User.StateCode
    );
    
    
}