objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Terms_And_Conditions__c.object
<CustomObject>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Terms_And_Conditions_Acceptance__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Accepted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
        <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TermsAndConditionsRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class TermsAndConditionsRemote {

    class TCData{
        Terms_And_Conditions__c tc;
        Datetime acceptedDate;
        Boolean isAccepted;
        Clinical_Trial_Profile__c trial;
        
    }

    @AuraEnabled
    public static String getPortalTcData() {
        try{
            return JSON.serialize(getTCData(TermsAndConditions.getPortalTC()));
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static String getTrialTcData(Id ctpId){
        try{
            TCData tcData = getTCData(TermsAndConditions.getTrialTC(ctpId));
            tcData.trial = SudyTrialService.getFullTrial(ctpId);
            return JSON.serialize(tcData);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static String getTC(Id tcId, String languageCode){
        try{
            TCData tcData = new TCData();
            tcData.tc = TermsAndConditions.getTC(tcId, languageCode);
            return JSON.serialize(tcData);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static void acceptTC(Id tcId){
        try{
            TermsAndConditions.acceptTC(tcId);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    private static TCData getTCData(Terms_And_Conditions__c tc){
        TCData tcData = new TCData();
        if(tc != null){
            tcData.tc = tc;
            Terms_And_Conditions_Acceptance__c tca = TermsAndConditions.getTCA(tc.Id);
            tcData.isAccepted = tca != null;
            if(tca != null) tcData.acceptedDate = tca.Accepted_Date__c;
        }
        return tcData;

    }


}