objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClinicProfileRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class ClinicProfileRemote {

    class InitData{
        Account clinic;
        List<StudySiteDetail> myStudies = new List<StudySiteDetail>();
        List<String> physicians;
    }
    
    class StudySiteDetail{
        Study_Site__c studySite;
        List<HCP_Enrollment__c> hcpEnrollments = new List<HCP_Enrollment__c>();
        List<StudyTotalPassed> statistics = new List<StudyTotalPassed>();
    }


    @AuraEnabled
    public static String getClinicProfileData(String clinicId){
        
        InitData initData = new InitData();
        initData.clinic = [
                SELECT Id, Name, BillingAddress, ShippingAddress, Fax, Phone
                FROM Account
                WHERE Id =: clinicId
        ];

        List<Study_Site__c> studySites = StudySiteService.getStudySitesForPI();
        List<HCP_Enrollment__c> hcpeList = HCPEnrollmentService.getHCPEnrollmentsForPI();
        Map<Id, List<HCP_Enrollment__c>> hcpeListByStudyIdMap = new Map<Id, List<HCP_Enrollment__c>>();
        for(HCP_Enrollment__c hcpe : hcpeList){
            List<HCP_Enrollment__c> studyHCPEList = hcpeListByStudyIdMap.get(hcpe.Study_Site__c);
            if(studyHCPEList == null) studyHCPEList = new List<HCP_Enrollment__c>();
            studyHCPEList.add(hcpe);
            hcpeListByStudyIdMap.put(hcpe.Study_Site__c, studyHCPEList);
        }

        Map<Id, Integer> preScreeningAllMap = ParticipantEnrollmentService.getPreScreeningsAllByTrial(clinicId);
        Map<Id, Integer> preScreeningPassedMap = ParticipantEnrollmentService.getPreScreeningsPassedByTrial(clinicId);
        Map<Id, Integer> mrrAlldMap = ParticipantEnrollmentService.getMRRAllByTrial(clinicId);
        Map<Id, Integer> mrrPasseddMap = ParticipantEnrollmentService.getMRRPassedByTrial(clinicId);
    
    
        Set<String> names = new Set<String>();
        for(Study_Site__c studySite : studySites) {
            List<HCP_Enrollment__c> studyHCPEList = hcpeListByStudyIdMap.get(studySite.Id);
            if(studyHCPEList != null && studyHCPEList.size() > 0) {
                StudySiteDetail ssd = new StudySiteDetail();
                ssd.hcpEnrollments = studyHCPEList;
                for(HCP_Enrollment__c enrollment : studyHCPEList) names.add(enrollment.HCP_Contact__r.Name);
                ssd.studySite = studySite;
                // if pre screening available:
                if(studySite.Clinical_Trial_Profile__r.Link_to_Pre_screening__c != null){
                    Integer preScreenigAll = preScreeningAllMap.get(studySite.Clinical_Trial_Profile__c);
                    Integer preScreenigPassed = preScreeningPassedMap.get(studySite.Clinical_Trial_Profile__c);
                    ssd.statistics.add(new StudyTotalPassed('pre-screening', preScreenigAll, preScreenigPassed));
                }
                // if mrr available
                if(studySite.Clinical_Trial_Profile__r.Link_to_Medical_Record_Review__c != null){
                    Integer mrrAll = mrrAlldMap.get(studySite.Clinical_Trial_Profile__c);
                    Integer mrrPassed = mrrPasseddMap.get(studySite.Clinical_Trial_Profile__c);
                    ssd.statistics.add(new StudyTotalPassed('mrr', mrrAll, mrrPassed));
                }
                initData.myStudies.add(ssd);
            }
        }

        initData.physicians = new List<String>();
        initData.physicians.addAll(names);
        initData.physicians.sort();

        return JSON.serialize(initData);
    }

}