objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Review_Completed_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Medical Record Review Completed by</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participant Enrollments (Medical Record Review Completed by)</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Review_Status__c</fullName>
        <label>Medical Record Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Name__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Participant Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Surname__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Participant Surname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MedicalRecordReviewRemote.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class MedicalRecordReviewRemote {

    public class InitData{
        public HCP_Enrollment__c hcpEnrollment;
        public Map<String, StudyActions.Action> actions;
    }

    @AuraEnabled
    public static String getInitData(String trialId){
        try{
            HCP_Enrollment__c hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
            //localize MRR
            if(hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r.Link_to_Medical_Record_Review__c != null){
                hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r.Link_to_Medical_Record_Review__c =
                        CommunityFacadeRemote.getLocalizedURL(hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r.Link_to_Medical_Record_Review__c);
            }
            if(hcpEnrollment == null) throw new CommunityServiceException('Data not found');
            new StudyActionsHCP(hcpEnrollment).checkAction(StudyActions.ACT_MEDICAL_RECORD_REVIEW);
            StudyActions sActions = new StudyActionsHCP(hcpEnrollment);
            InitData initData = new InitData();
            initData.hcpEnrollment = hcpEnrollment;
            initData.actions = sActions.actions;
            //check accessibility;
            return JSON.serialize(initData);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }


    public class SearchPEResult{
        public Participant_Enrollment__c  pe;
        public String result;
    }

    @AuraEnabled
    public static String createParticipantEnrollment(Id trialId, String participantId, String firstName, String lastName){
        Savepoint sp = Database.setSavepoint();
        try{
            Clinical_Trial_Profile__c trial = SudyTrialService.getFullTrial(trialId);
            HCP_Enrollment__c hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
            SearchPEResult peResult = new SearchPEResult();
            //find already created participant enrollments:
            peResult.pe = ParticipantEnrollmentService.findParticipantEnrollment(hcpEnrollment, participantId);
            //If participant is null then create new
            if (peResult.pe == null) {
                peResult.pe = ParticipantEnrollmentService.createParticipantEnrollment(trial, hcpEnrollment, participantId);
                peResult.pe.Participant_Name__c = firstName;
                peResult.pe.Participant_Surname__c = lastName;
                peResult.result = 'New';
            //} else if (peResult.pe.HCP__c != hcpeId) {
            //    peResult.result = 'Other HCP';
            } else if (peResult.pe.Participant_Status__c == ParticipantEnrollmentService.PART_STATUS_FAILED_REVIEW) {
                peResult.result = 'MRR Fail';
            } else if (peResult.pe.Participant_Status__c == ParticipantEnrollmentService.PART_STATUS_FAILED_REFERRAL) {
                if(trial.Link_to_Medical_Record_Review__c == null){
                    peResult.result = 'PES Fail';
                }else{
                    peResult.result = 'MRR Pass PES Fail';
                }
            } else if (peResult.pe.Participant_Status__c == ParticipantEnrollmentService.PART_STATUS_PENDING_REFERRAL) {
                peResult.result = 'PES Pending';
            } else {
                peResult.result = 'Completed';
            }
            return JSON.serialize(peResult);
        }catch (Exception e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static String setMRRStatus(String peJSON, String status){
        Savepoint sp = Database.setSavepoint();
        try{
            Participant_Enrollment__c participantEnrollment = (Participant_Enrollment__c)JSON.deserialize(peJSON, Participant_Enrollment__c.class);
            participantEnrollment.Medical_Record_Review_Status__c = status;
            participantEnrollment.Medical_Record_Review_Completed_by__c = CommunityService.getUserContact().Id;
            if(status == ParticipantEnrollmentService.MRR_STATUS_PASS){
                participantEnrollment.Participant_Status__c = ParticipantEnrollmentService.PART_STATUS_PENDING_REFERRAL;
            }else{
                participantEnrollment.Participant_Status__c = ParticipantEnrollmentService.PART_STATUS_FAILED_REVIEW;
            }
            System.debug('PE: ' + JSON.serialize(participantEnrollment));
            upsert participantEnrollment;
            return JSON.serialize(participantEnrollment);
        }catch (Exception e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }



}