objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>HCP Status per clinical trial by PI</description>
        <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
        <label>HCP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>On Hold (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending Orientation</fullName>
                </value>
                <value>
                    <fullName>Declined (Approval)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Approval)</fullName>
                </value>
                <value>
                    <fullName>Declined (Activation)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Activation)</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Activated (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Admin)</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudyActionsHCP.cls
/**
 * Created by Leonid Bartenev
 */

public class StudyActionsHCP extends StudyActions{

    public StudyActionsHCP(HCP_Enrollment__c hcpEnrollment){
        this(
                hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r,
                hcpEnrollment.Study_Site__r,
                hcpEnrollment
        );
    }

    public StudyActionsHCP(Participant_Enrollment__c pe){
        this(
                pe.Study_Site__r.Clinical_Trial_Profile__r,
                pe.Study_Site__r,
                pe.HCP__r
        );
    }

    public StudyActionsHCP(Clinical_Trial_Profile__c study, Study_Site__c studySite, HCP_Enrollment__c hcpEnrollment){
        super(study,studySite, hcpEnrollment, CommunityService.USER_MODE_HCP);

        //init actions:
        actions.put(ACT_MEDICAL_RECORD_REVIEW, new Action(
                ACT_MEDICAL_RECORD_REVIEW,
                LABEL_MEDICAL_RECORD_REVIEW,
                'chart-review-sent',
                new List<DisableReason>{
                        tcAcceptanceRequiredReason,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason
                }
        ));

        actions.put(ACT_EXCLUDE_FROM_REFERRING, new Action(
                ACT_EXCLUDE_FROM_REFERRING,
                LABEL_EXCLUDE_FROM_REFERRING,
                '',
                new List<DisableReason>{
                        level2AndLowReason,
                        tcAcceptanceRequiredReason,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason
                }
        ));

        actions.put(ACT_UNDO_EXCLUDE_FROM_REFERRING, new Action(
                ACT_UNDO_EXCLUDE_FROM_REFERRING,
                LABEL_UNDO_EXCLUDE_FROM_REFERRING,
                '',
                new List<DisableReason>{
                        level2AndLowReason,
                        tcAcceptanceRequiredReason,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason
                }
        ));

        actions.put(ACT_REFER_TO_THIS_STUDY, new Action(
                ACT_REFER_TO_THIS_STUDY,
                LABEL_REFER_TO_THIS_STUDY,
                'referral',
                new List<DisableReason>{
                        level2AndLowReason,
                        tcAcceptanceRequiredReason,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason
                }
        ));

        actions.put(ACT_REFER, new Action(
                ACT_REFER,
                LABEL_REFER,
                'referral',
                new List<DisableReason>{
                        level2AndLowReason,
                        tcAcceptanceRequiredReason,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason
                }
        ));

        List<String> shareStatuses = new List<String>{
                HCPEnrollmentService.HCP_S_ACTIVATED,
                HCPEnrollmentService.HCP_S_ACTIVATED_A,
                HCPEnrollmentService.HCP_S_APPROVAL_PENDING,
                HCPEnrollmentService.HCP_S_ACTIVATION_PENDING,
                HCPEnrollmentService.HCP_S_ACTIVATION_PENDING_O,
                HCPEnrollmentService.HCP_S_ON_HOLD_A,
                HCPEnrollmentService.HCP_S_ON_HOLD_ACCEPTANCE,
                HCPEnrollmentService.HCP_S_ON_HOLD_ACTIVATION,
                HCPEnrollmentService.HCP_S_ON_HOLD_APPROVAL,
                HCPEnrollmentService.HCP_S_DEACTIVATED_A,
                HCPEnrollmentService.HCP_S_DECLINED_ACCEPTANCE
        };
    
        actions.put(ACT_SHARE, new Action(
                ACT_SHARE,
                LABEL_SHARE,
                'share',
                new List<DisableReason>{
                        new DisableReason(
                                hcpEnrollment== null || !shareStatuses.contains(hcpEnrollment.Status__c),
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_HCP_STATUS
                        )
                }
        ));

        List<String> findStudySiteStatuses = new List<String>{
                HCPEnrollmentService.HCP_S_INVITATION_SENT,
                HCPEnrollmentService.HCP_S_DECLINED_ACCEPTANCE,
                HCPEnrollmentService.HCP_S_NON_RESPONCIVE_A
        };
    
        actions.put(ACT_FIND_STUDY_SITES, new Action(
                ACT_FIND_STUDY_SITES,
                LABEL_FIND_STUDY_SITES,
                'referred-clinic',
                new List<DisableReason>{
                        studyNoLongerEnrollingReason,
                        new DisableReason(
                                hcpEnrollment== null || !findStudySiteStatuses.contains(hcpEnrollment.Status__c),
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_HCP_STATUS
                        )
                },
                'primary'
        ));

        actions.put(ACT_NO_THANKS, new Action(
                ACT_NO_THANKS,
                LABEL_NO_THANKS,
                'icon-disabled',
                new List<DisableReason>{
                        studyNoLongerEnrollingReason,
                        studySiteOnHoldReason,
                        new DisableReason(
                                hcpEnrollment== null || hcpEnrollment.Status__c != HCPEnrollmentService.HCP_S_INVITATION_SENT,
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_HCP_STATUS
                        )
                },
                'secondary'
        ));
    
    
        actions.put(ACT_SEND_SITE_REQUEST, new Action(
                ACT_SEND_SITE_REQUEST,
                LABEL_SEND_SITE_REQUEST,
                '',
                new List<DisableReason>{
                        level1AndLowReason,
                        tcAcceptanceRequiredReason,
                        new DisableReason(
                                hcpEnrollment== null || !findStudySiteStatuses.contains(hcpEnrollment.Status__c),
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_HCP_STATUS
                        ),
                        studyNoLongerEnrollingReason
                }
        ));


        //prepare study item actions list:
        //MRR, Referring
        if(hcpEnrollment!= null && HCPEnrollmentService.STATUS_GROUP_ACTIVATED.contains(hcpEnrollment.Status__c)){
            if(study.Link_to_Medical_Record_Review__c != null) studyListViewItemActions.add(actions.get(ACT_MEDICAL_RECORD_REVIEW));
            if(study.Link_to_Pre_screening__c != null) studyListViewItemActions.add(actions.get(ACT_REFER_TO_THIS_STUDY));
            if(study.Link_to_Medical_Record_Review__c != null && study.Link_to_Pre_screening__c == null){
                studyListViewItemActions.add(actions.get(ACT_REFER));
            }
        }

        //Accept TC
        List<String> tcStatuses = new List<String>{
                HCPEnrollmentService.HCP_S_INVITATION_SENT,
                HCPEnrollmentService.HCP_S_NON_RESPONCIVE_A,
                HCPEnrollmentService.HCP_S_DECLINED_ACCEPTANCE,
                HCPEnrollmentService.HCP_S_DECLINED_APPROVAL,
                HCPEnrollmentService.HCP_S_DECLINE_ACTIVATION,
                HCPEnrollmentService.HCP_S_DECLINED_A

        };
        if(hcpEnrollment!= null && tcStatuses.contains(hcpEnrollment.Status__c) && (isTCAcceptanceRequired)){
            studyListViewItemActions.add(actions.get(ACT_VIEW_TC));
        }

        //Find study sites:
        if(hcpEnrollment!= null && findStudySiteStatuses.contains(hcpEnrollment.Status__c) && !isTCAcceptanceRequired){
            studyListViewItemActions.add(actions.get(ACT_FIND_STUDY_SITES));
        }

        //No thanks:
        if(hcpEnrollment!= null && hcpEnrollment.Status__c == HCPEnrollmentService.HCP_S_INVITATION_SENT){
            studyListViewItemActions.add(actions.get(ACT_NO_THANKS));
        }

        //Share
        if(hcpEnrollment!= null && shareStatuses.contains(hcpEnrollment.Status__c)) studyListViewItemActions.add(actions.get(ACT_SHARE));


        //prepare study detail actions list:
        if(study.Link_to_Medical_Record_Review__c != null) studyDetailActions.add(actions.get(ACT_MEDICAL_RECORD_REVIEW));
        if(study.Link_to_Pre_screening__c != null) studyDetailActions.add(actions.get(ACT_REFER_TO_THIS_STUDY));
        if(study.Link_to_Medical_Record_Review__c != null && study.Link_to_Pre_screening__c == null){
            studyDetailActions.add(actions.get(ACT_REFER));
        }
        if(study.Terms_And_Conditions_ID__c != null) studyDetailActions.add(actions.get(ACT_VIEW_TC));
        studyDetailActions.add(actions.get(ACT_SHARE));

        //prepare bottom bar actions:
        if(hcpEnrollment!= null && findStudySiteStatuses.contains(hcpEnrollment.Status__c)){
            if(isTCAcceptanceRequired){
                studyDetailBottomBarActions.add(actions.get(ACT_VIEW_TC));
            }else{
                studyDetailBottomBarActions.add(actions.get(ACT_FIND_STUDY_SITES));
            }
            if(hcpEnrollment.Status__c == HCPEnrollmentService.HCP_S_INVITATION_SENT){
                studyDetailBottomBarActions.add(actions.get(ACT_NO_THANKS));
            }
        }
    }

}