objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; HCP__r.HCP_Contact__c ,HCP__r.HCP_Contact__r.FirstName&amp;&quot; &quot;&amp;  HCP__r.HCP_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HCP Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Review_Status__c</fullName>
        <label>Medical Record Review Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pre_screening_Status__c</fullName>
        <label>Pre-screening Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ReportsRemote.cls
/**
 * Created by Leonid Bartenev
 */

public class ReportsRemote {
    
    class InitData{
        ReportsFilterData filterData;
        Analitics analitics;
    }
    
    public class Analitics{
        List<DonutItem> mrrPassedFailed = new List<DonutItem>();
        List<DonutItem> preScreeningPassedFailed = new List<DonutItem>();
        List<DonutItem> studyOrientationAttVsNotAtt = new List<DonutItem>();
    }
    
    class ReportsFilterData{
        List<LabelValueItem> studies;
        List<LabelValueItem> studySites;
        List<LabelValueItem> referringClinics;
        List<LabelValueItem> dateRanges = DateRangeFilterData.getRanges();
    }
    
    @AuraEnabled
    public static String getInitData(String trialId, String userMode){
        try{
            Id userContactId = CommunityService.getUserContact().Id;
    
            ReportsFilterData reportsFilterData = new ReportsFilterData();
            Map<Id, Clinical_Trial_Profile__c> trialsMap = new Map<Id, Clinical_Trial_Profile__c>(TrialService.getAvailableTrials(userMode));
            //init trials
            reportsFilterData.studies = new List<LabelValueItem>();
            reportsFilterData.studies.add(new LabelValueItem(Label.PG_MRRL_L_All_studies, null));
            for(String id : trialsMap.keySet()){
                Clinical_Trial_Profile__c trial = trialsMap.get(id);
                reportsFilterData.studies.add(new LabelValueItem(trial.Study_Code_Name__c, trial.Id));
            }
    
            List<Id> trialIds;
            if(trialId != null) {
                trialIds = new List<Id>{trialId};
            }else{
                trialIds = new List<Id>(trialsMap.keySet());
            }
    
            //init study sites:
            reportsFilterData.studySites = new List<LabelValueItem>();
            reportsFilterData.studySites.add(new LabelValueItem(Label.PG_Report_L_All_study_sites, null));
            if(userMode == CommunityService.USER_MODE_HCP){
                List<Study_Site__c> studySites = StudySiteService.getStudySitesForHCP(trialIds);
                for(Study_Site__c ss : studySites) reportsFilterData.studySites.add(new LabelValueItem(ss.Name, ss.Id));
            }
    
            //init referring clinics
            reportsFilterData.referringClinics = new List<LabelValueItem>();
            reportsFilterData.referringClinics.add(new LabelValueItem(Label.PG_Report_L_All_referring_clinics, null));
            for(Account clinic : HCPEnrollmentService.getReferringClinics(trialIds)){
                reportsFilterData.referringClinics.add(new LabelValueItem(clinic.Name, clinic.Id));
            }
    
            InitData initData = new InitData();
            initData.filterData = reportsFilterData;
            initData.analitics = getAnaliticsData(trialId, null, null, null, userMode);
            return JSON.serialize(initData);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static String getAnaliticsJSON(String studyId, String studySiteId, String referringClinicId, String dateRange, String userMode){
        try{
            return JSON.serialize(getAnaliticsData(studyId, studySiteId, referringClinicId, dateRange, userMode));
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    public static Analitics getAnaliticsData(String studyId, String studySiteId, String referringClinicId, String dateRange, String userMode){
        String filter = '';
        String filterHCPE = '';
        if(studyId != null) studyId = studyId.trim();
        if(!String.isEmpty(studyId)) {
            filter += ' AND Study_Site__r.Clinical_Trial_Profile__c = \'' + studyId + '\'';
            filterHCPE += ' AND Study_Site__r.Clinical_Trial_Profile__c = \'' + studyId + '\'';
        }
        if(!String.isEmpty(studySiteId)) {
            filter += ' AND Study_Site__c=\'' + studySiteId + '\'';
            filterHCPE += ' AND Study_Site__c=\'' + studySiteId + '\'';
        }
        if(!String.isEmpty(referringClinicId)) {
            filter += ' AND HCP__R.HCP_Contact__r.AccountId=\'' + referringClinicId + '\'';
            filterHCPE += ' AND HCP_Contact__r.AccountId=\'' + referringClinicId + '\'';
        }
        if(!String.isEmpty(dateRange)) {
            filter += ' AND CreatedDate ' + dateRange;
            filterHCPE += ' AND CreatedDate ' + dateRange;
        }
        List<Participant_Enrollment__c> peList = ParticipantEnrollmentService.getPEnrolmentsCommon(userMode, filter);
        
    
        Integer mrrPassed = 0;
        Integer mrrFailed = 0;
        Integer preScreeningPassed = 0;
        Integer preScreeningFailed = 0;
        Integer orAttended = 0;
        Integer orNoAttended = 0;
        
        System.debug('REC count: ' + peList.size());
        for(Participant_Enrollment__c pe : peList){
            if(pe.Medical_Record_Review_Status__c == ParticipantEnrollmentService.MRR_STATUS_PASS) mrrPassed++;
            if(pe.Medical_Record_Review_Status__c == ParticipantEnrollmentService.MRR_STATUS_FAIL) mrrFailed++;
            if(pe.Pre_screening_Status__c == ParticipantEnrollmentService.PES_STATUS_PASS) preScreeningPassed++;
            if(pe.Pre_screening_Status__c == ParticipantEnrollmentService.PES_STATUS_FAIL) preScreeningFailed++;
        }
        
        Analitics analitics = new Analitics();
        analitics.mrrPassedFailed.addAll(new List<DonutItem>{
                new DonutItem(Label.PG_MRR_R_Passed, mrrPassed , DonutItem.Type.SUCCSESS),
                new DonutItem(Label.PG_MRR_R_Failed, mrrFailed , DonutItem.Type.DECLINED)
        });
        analitics.preScreeningPassedFailed.addAll(new List<DonutItem>{
                new DonutItem(Label.PG_PrS_R_Passed, preScreeningPassed , DonutItem.Type.SUCCSESS),
                new DonutItem(Label.PG_PrS_R_Failed, preScreeningFailed , DonutItem.Type.DECLINED)
        });
        analitics.studyOrientationAttVsNotAtt.addAll(new List<DonutItem>{
                new DonutItem(Label.PG_Or_R_Attended, HCPEnrollmentService.getAttendedRequiredCount(userMode, true, filterHCPE) , DonutItem.Type.SUCCSESS),
                new DonutItem(Label.PG_Or_R_Not_attended, HCPEnrollmentService.getAttendedRequiredCount(userMode, false, filterHCPE) , DonutItem.Type.DECLINED)
        });
        
        return analitics;
    }

}