objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>userCommunityMode__c</fullName>
        <description>Current view point for Community</description>
        <label>User Community Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>userCommunytyType__c</fullName>
        <description>User types for community - HCP / PI / Participant</description>
        <inlineHelpText>Select user types for community</inlineHelpText>
        <label>User Community Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>HCP Status per clinical trial by PI</description>
        <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
        <label>HCP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>On Hold (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending Orientation</fullName>
                </value>
                <value>
                    <fullName>Declined (Approval)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Approval)</fullName>
                </value>
                <value>
                    <fullName>Declined (Activation)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Activation)</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Activated (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Admin)</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site_PI_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site PI Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP Enrollments (PI Contact)</relationshipLabel>
        <relationshipName>HCP_Enrollments_SS_PI_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Status_History__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Status has been changed.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HCP_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP Enrollment</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>StatusHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewStatus__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>New Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Status History</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/HCPEnrollmentTriggerHandler.cls
/**
 * Created by D.Yasinskyi on 23.02.2018
 */
public without sharing class HCPEnrollmentTriggerHandler {
    
    public static void prepareAdditionalFieldsBeforeInsertUpdate(){
        if(Trigger.isBefore && (Trigger.isUpdate || Trigger.isInsert)){
            List<HCP_Enrollment__c> hcpeList = (List<HCP_Enrollment__c>)Trigger.new;
            Set<Id> ssIds = new Set<Id>();
            for(HCP_Enrollment__c hcpe : hcpeList) if(hcpe.Study_Site__c != null) ssIds.add(hcpe.Study_Site__c);
            Map<Id, Study_Site__c> studySiteMap = new Map<Id, Study_Site__c>([
                    SELECT Id, Principal_Investigator__c,
                            Clinical_Trial_Profile__c
                    FROM Study_Site__c WHERE Id IN: ssIds
            ]);
            for(HCP_Enrollment__c hcpe : hcpeList){
                if(hcpe.Study_Site__c != null){
                    Study_Site__c ss = studySiteMap.get(hcpe.Study_Site__c);
                    if(ss != null) {
                        hcpe.Study_Site_PI_Contact__c = ss.Principal_Investigator__c;
                        hcpe.Clinical_Trial_Profile__c = ss.Clinical_Trial_Profile__c;
                    }
                }
            }
        }
    }

    public static void onBeforeDelete(Map<Id, HCP_Enrollment__c> oldEnrollments) {
        //delete status history
        deleteStatusHistory(oldEnrollments);
    }
    public static void onAfterInsert(List<HCP_Enrollment__c> enrollments) {
        //send notification to HCP users [new HCP enrollment] or create new User(if not exist)
        sendNotification(enrollments);
        //prepopulate contacts for HCP procces
        prepopulateUserMode(enrollments);
        
        //switch user mode
        List<Contact> contacts = new List<Contact>();
        for(HCP_Enrollment__c hcpe : [SELECT Id, HCP_Contact__c FROM HCP_Enrollment__c WHERE Id IN: enrollments]){
            contacts.add(new Contact(
                    Id = hcpe.HCP_Contact__c,
                    userCommunityMode__c = CommunityService.USER_MODE_HCP
            ));
        }
        update contacts;
    }
    
    public static void onAfterUpdate(Map<Id, HCP_Enrollment__c> newEnrollments, Map<Id, HCP_Enrollment__c> oldEnrollments) {
        //send notification to HCP users [new HCP enrollment]
        sendNotificationOnUpdate(newEnrollments, oldEnrollments);
        //prepopulate contacts for HCP procces
        prepopulateUserModeOnUpdate(newEnrollments, oldEnrollments);
        //treck status history
        createStatusHistory(newEnrollments, oldEnrollments);
    }

    private static void sendNotification(List<HCP_Enrollment__c> enrollments) {
        //prepare community users map:
        Set<Id> contactIds = new Set<Id>();
        List<HCP_Enrollment__c> processedHCPEList = new List<HCP_Enrollment__c>();
        for (HCP_Enrollment__c enrol : enrollments) {
            if (enrol.HCP_Contact__c != null && enrol.Status__c == HCPEnrollmentService.HCP_S_INVITATION_SENT) {
                contactIds.add(enrol.HCP_Contact__c);
                processedHCPEList.add(enrol);
            }
        }
        if (contactIds.isEmpty()) return;
        Map<Id, User> communityUsersMap = new Map<Id, User>();
        for (User usr : CommunityService.getCommunityUsersByContactIds(contactIds)) communityUsersMap.put(usr.ContactId, usr);
        
        //prepare lists:
        Set<Id> contactIdsForCreateUser = new Set<Id>();
        Map<Id, String> hcpeMapForSend = new Map<Id, String>();
        for (HCP_Enrollment__c hcpe : processedHCPEList) {
            if (communityUsersMap.containsKey(hcpe.HCP_Contact__c)) {
                hcpeMapForSend.put(hcpe.Id, hcpe.HCP_Contact__c);
            } else {
                contactIdsForCreateUser.add(hcpe.HCP_Contact__c);
            }
        }

        //process lists:
        if (!contactIdsForCreateUser.isEmpty()) CommunityService.createPortalUsers(contactIdsForCreateUser);
        if (!hcpeMapForSend.isEmpty()) SendEmailTemplate.sendEmailNotification(CommunityService.COMMUNITY_ET_HCP, hcpeMapForSend);
    }

    private static void sendNotificationOnUpdate(Map<Id, HCP_Enrollment__c> newEnrollments, Map<Id, HCP_Enrollment__c> oldEnrollments) {

        List<HCP_Enrollment__c> enrolmentsToSendNotification = new List<HCP_Enrollment__c>();

        for (HCP_Enrollment__c enrollment: newEnrollments.values()) {

            if (oldEnrollments.get(enrollment.Id).HCP_Contact__c != enrollment.HCP_Contact__c
                    || (enrollment.Status__c == HCPEnrollmentService.HCP_S_INVITATION_SENT
                    && oldEnrollments.get(enrollment.Id).Status__c != enrollment.Status__c)
                    ) {
                enrolmentsToSendNotification.add(enrollment);
            }
        }
        sendNotification(enrolmentsToSendNotification);
    }

    private static void prepopulateUserMode(List<HCP_Enrollment__c> enrollments) {

        Set<Id> hcpEContactIds = new Set<Id>();

        for (HCP_Enrollment__c enrol : enrollments) {
            if (enrol.HCP_Contact__c != null) {
                hcpEContactIds.add(enrol.HCP_Contact__c);
            }
        }

        if (hcpEContactIds.isEmpty()) return;

        Map<Id, Contact> contactsToUpdate = new Map<Id, Contact>();

        for (Contact hcpContact : CommunityService.getContactsByUserContactIds(hcpEContactIds)) {

            String userType = hcpContact.userCommunytyType__c;
            String userMode = hcpContact.userCommunityMode__c;

            if (userMode == null || userType == null || !userType.contains(CommunityService.USER_MODE_HCP)) {

                if (userMode == null) {
                    hcpContact.userCommunityMode__c = CommunityService.USER_MODE_HCP;
                }
                if (userType == null || !userType.contains(CommunityService.USER_MODE_HCP)) {

                    if (userType == null) {
                        hcpContact.userCommunytyType__c = CommunityService.USER_MODE_HCP;
                    } else {
                        hcpContact.userCommunytyType__c = userType + ';' + CommunityService.USER_MODE_HCP;
                    }
                }
                if (!contactsToUpdate.containsKey(hcpContact.Id)) {
                    contactsToUpdate.put(hcpContact.Id, hcpContact);
                }
            }
        }
        update contactsToUpdate.values();
    }

    private static void prepopulateUserModeOnUpdate(Map<Id, HCP_Enrollment__c> newEnrollments, Map<Id, HCP_Enrollment__c> oldEnrollments) {

        List<HCP_Enrollment__c> enrollmentsToPopulate = new List<HCP_Enrollment__c>();
        for (HCP_Enrollment__c enrollment: newEnrollments.values()) {
            if (oldEnrollments.get(enrollment.Id).HCP_Contact__c != enrollment.HCP_Contact__c) {
                enrollmentsToPopulate.add(enrollment);
            }
        }
        prepopulateUserMode(enrollmentsToPopulate);
    }

    private static void createStatusHistory(Map<Id, HCP_Enrollment__c> newEnrollments, Map<Id, HCP_Enrollment__c> oldEnrollments) {

        List<Status_History__c> hcpEHistoryList = new List<Status_History__c>();

        for (HCP_Enrollment__c enrollment: newEnrollments.values()) {

            if (oldEnrollments.get(enrollment.Id).Status__c != enrollment.Status__c) {

                hcpEHistoryList.add(new Status_History__c(
                        Date__c = Datetime.now(),
                        HCP_Enrollment__c = enrollment.Id,
                        NewStatus__c = enrollment.Status__c
                ));
            }
        }

        insert hcpEHistoryList;
    }

    private static void deleteStatusHistory(Map<Id, HCP_Enrollment__c> oldEnrollments) {
        delete [SELECT Id FROM Status_History__c WHERE HCP_Enrollment__c IN :oldEnrollments.keySet()];
    }
}