objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Official_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Official Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Official Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>Title of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Title</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Languages</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <formula>Study_Site__r.Is_Virtual_Study_Site__c</formula>
        <label>Is Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Participant&apos;s First Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s First Name</inlineHelpText>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language_Preference_Code__c</fullName>
        <label>Language Preference Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>zh_CN</fullName>
                </value>
                <value>
                    <fullName>zh_TW</fullName>
                </value>
                <value>
                    <fullName>da</fullName>
                </value>
                <value>
                    <fullName>nl_NL</fullName>
                </value>
                <value>
                    <fullName>fi</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>ja</fullName>
                </value>
                <value>
                    <fullName>ko</fullName>
                </value>
                <value>
                    <fullName>pt_BR</fullName>
                </value>
                <value>
                    <fullName>ru</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>sv</fullName>
                </value>
                <value>
                    <fullName>th</fullName>
                </value>
                <value>
                    <fullName>ar</fullName>
                </value>
                <value>
                    <fullName>bg</fullName>
                </value>
                <value>
                    <fullName>cs</fullName>
                </value>
                <value>
                    <fullName>en_GB</fullName>
                </value>
                <value>
                    <fullName>el</fullName>
                </value>
                <value>
                    <fullName>es_MX</fullName>
                </value>
                <value>
                    <fullName>iw</fullName>
                </value>
                <value>
                    <fullName>hu</fullName>
                </value>
                <value>
                    <fullName>in</fullName>
                </value>
                <value>
                    <fullName>no</fullName>
                </value>
                <value>
                    <fullName>pl</fullName>
                </value>
                <value>
                    <fullName>ro</fullName>
                </value>
                <value>
                    <fullName>tr</fullName>
                </value>
                <value>
                    <fullName>uk</fullName>
                </value>
                <value>
                    <fullName>vi</fullName>
                </value>
                <value>
                    <fullName>en_US</fullName>
                    <default>true</default>
                    <label>en_US</label>
                </value>
                <value>
                    <fullName> en_US</fullName>
                    <isActive>false</isActive>
                    <label> en_US</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Participant&apos;s Last Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s Last Name</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; HCP__r.HCP_Contact__c ,HCP__r.HCP_Contact__r.FirstName&amp;&quot; &quot;&amp;  HCP__r.HCP_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HCP Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <formula>Study_Site__r.Is_Virtual_Study_Site__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Referring_HCP_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referring HCP Staffs</relationshipLabel>
        <relationshipName>Referring_HCP_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HCP_Enrollment__c</fullName>
        <label>HCP Enrollment</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Referring HCP Staffs</relationshipLabel>
        <relationshipName>Referring_HCP_Staffs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Referring HCP Staff</label>
    <nameField>
        <displayFormat>HCPS-{000000}</displayFormat>
        <label>Referring HCP Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referring HCP Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site_Staff__c.object
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&apos;s team</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clinical Trial Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Site Staff</relationshipLabel>
        <relationshipName>Site_Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Virtual_Study_Site__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Virtual Study Site</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Phone number referenced in the email for Virtual Trial Participants</inlineHelpText>
        <label>Study Site Phone</label>
        <type>Phone</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ParametersDataProvider.cls
/**
 * Created by Leonid Bartenev
 *
 * Email Template Parameters Data Provider
 *
 */

public class ParametersDataProvider {
    
    public static final String DEFAULT_LANGUAGE = 'en_US';
    
    public Map<String, String> parameters;
    public String userMode;
    public Boolean isDelegate = false;
    public List<DelegateLevelWrapper> delegateLevelsPI = new List<DelegateLevelWrapper>();
    public List<DelegateLevelWrapper> delegateLevelsHCP = new List<DelegateLevelWrapper>();
    
    
    
    public ParametersDataProvider(Id sourceId, String userType, String outputMode){
        userMode = userType;
        if(sourceId != null){
            if (sourceId.getSobjectType() == Participant_Enrollment__c.getSObjectType()) {
                initParamsFromPE(sourceId);
            } else if (sourceId.getSobjectType() == HCP_Enrollment__c.getSObjectType()) {
                initParamsFromHCPE(sourceId);
            } else if (sourceId.getSobjectType() == Study_Site__c.getSObjectType()) {
                initParamsFromSS(sourceId);
            } else if(sourceId.getSobjectType() == Contact.getSObjectType()){
                initParamsFromContact(sourceId);
            } else if(sourceId.getSobjectType() == User.getSObjectType()){
                initParamsFromUser(sourceId);
            }
        }else{
            initDummyParams();
        }
        
        String clinicalResearchCommunityURL = 'IQVIA Clinical Research Community at https://www.clinicalresearch.com';
        if(outputMode == 'HTML') clinicalResearchCommunityURL = '<a href="https://www.clinicalresearch.com" target="_blank">IQVIA Clinical Research Community</a>';
        parameters.put('CRCommunityURL', clinicalResearchCommunityURL);
        
        System.debug('PARAMS: ' + JSON.serializePretty(parameters));
    }
    
    private void initParamsFromPE(Id sourceId){
        Participant_Enrollment__c pe = [
                SELECT Id, Name,
                        HCP__r.HCP_Contact__c,
                        HCP__r.HCP_Contact__r.Name,
                        HCP__r.HCP_Contact__r.Salutation,
                        HCP__r.HCP_Contact__r.Language__c,
                        Participant__r.Contact__c,
                        Participant__r.Contact__r.Name,
                        Participant__r.Contact__r.Salutation,
                        Participant__r.Contact__r.Language__c,
                        Participant__r.Language_Preference_Code__c,
                        Participant__r.First_Name__c,
                        Participant__r.Last_Name__c,
                        Study_Site__r.Name,
                        Study_Site__r.Principal_Investigator__r.Name,
                        Study_Site__r.Principal_Investigator__r.Salutation,
                        Study_Site__r.Principal_Investigator__r.Language__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Official_Title__c,
                        Study_Site__r.Study_Site_Phone__c,
                        Is_Virtual_Study_Site__c,
                        HCP__c
                FROM Participant_Enrollment__c
                WHERE Id =: sourceId OR Participant__r.Contact__c =: sourceId LIMIT 1
        ];
        
        parameters = new Map<String, String>{
                'PIName' => getFullContactName(pe.Study_Site__r.Principal_Investigator__r),
                'PILanguage' => pe.Study_Site__r.Principal_Investigator__r.Language__c,
                'ParticipantName' => getFullParticipantName(pe.Participant__r),
                'ParticipantLanguage' => getParticipantLanguage(pe.Participant__r),
                'IsVirtual' => pe.Is_Virtual_Study_Site__c + ''
        };
        
        if(pe.HCP__c != null){
            parameters.putAll(new Map<String, String>{
                    'HCPName' => getFullContactName(pe.HCP__r.HCP_Contact__r),
                    'HCPLanguage' => pe.HCP__r.HCP_Contact__r.Language__c
            });
        }
    
        TranslateHelper.translate(pe, getUserLanguage());
    
        parameters.putAll(new Map<String, String>{
                'PEName' => pe.Name,
                'StudyName' => pe.Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                'StudyTitle' => pe.Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                'StudySiteName' => pe.Study_Site__r.Name,
                'HCP' => pe.HCP__c,
                'SitePhoneNumber' => pe.Study_Site__r.Study_Site_Phone__c
        });
    }
    
    private void initParamsFromHCPE(Id hcpeId){
        HCP_Enrollment__c hcpe = [
                SELECT Id, Name,
                        HCP_Contact__r.Name,
                        HCP_Contact__r.Salutation,
                        HCP_Contact__r.Language__c,
                        Study_Site__r.Name,
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Official_Title__c,
                        Study_Site__r.Principal_Investigator__c,
                        Study_Site__r.Principal_Investigator__r.Language__c,
                        Study_Site__r.Principal_Investigator__r.Name,
                        Study_Site__r.Principal_Investigator__r.Salutation,
                        Study_Site__r.Study_Site_Phone__c,
                        HCP_Contact__c
                FROM HCP_Enrollment__c
                WHERE Id = :hcpeId
        ];
    
        parameters = new Map<String, String>{
                'GuestName' => TranslateHelper.getLabelValue('Email_Guest_User_Name'),
                'GuestLanguage' => hcpe.HCP_Contact__r.Language__c,
                'PIName' =>  getFullContactName(hcpe.Study_Site__r.Principal_Investigator__r),
                'HCPName' => getFullContactName(hcpe.HCP_Contact__r),
                'PILanguage' => hcpe.Study_Site__r.Principal_Investigator__r.Language__c,
                'HCPLanguage' => hcpe.HCP_Contact__r.Language__c
        };
    
        TranslateHelper.translate(hcpe, getUserLanguage());
    
        parameters.putAll(new Map<String, String>{
                'StudySiteName' => hcpe.Study_Site__r.Name,
                'StudyName' => hcpe.Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                'StudyTitle' => hcpe.Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                'SitePhoneNumber' => hcpe.Study_Site__r.Study_Site_Phone__c
        });
        

    }
    
    private void initParamsFromSS(Id ssId){
        Study_Site__c ss = [
                SELECT Id, Name,
                        Principal_Investigator__r.Name,
                        Principal_Investigator__r.Salutation,
                        Principal_Investigator__r.Language__c,
                        Principal_Investigator__c,
                        Clinical_Trial_Profile__r.Study_Title__c,
                        Clinical_Trial_Profile__r.Study_Code_Name__c,
                        Study_Site_Phone__c
                FROM Study_Site__c
                WHERE Id = :ssId
        ];
    
        parameters = new Map<String, String>{
                'PIName' => getFullContactName(ss.Principal_Investigator__r),
                'PILanguage' => ss.Principal_Investigator__r.Language__c
        };
    
        TranslateHelper.translate(ss, getUserLanguage());
    
        parameters.putAll(new Map<String, String>{
                'StudySiteName' => ss.Name,
                'StudyName' => ss.Clinical_Trial_Profile__r.Study_Code_Name__c,
                'StudyTitle' => ss.Clinical_Trial_Profile__r.Study_Title__c,
                'SitePhoneNumber' => ss.Study_Site_Phone__c
        });

    }
    
    private void initParamsFromContact(Id contactId){
        Contact cnt = [
                SELECT Id, Name, Salutation,
                        Language__c,
                        userCommunityMode__c,
                        UserCommunityIsDelegate__c
                FROM Contact
                WHERE Id =: contactId
        ];
        initDelegates(cnt);
        isDelegate = cnt.UserCommunityIsDelegate__c;
        userMode = cnt.userCommunityMode__c;
        if(userMode == CommunityService.USER_MODE_PI){
            parameters = new Map<String, String>{
                    'PIName' => getFullContactName(cnt),
                    'PILanguage' => cnt.Language__c
            };
    
        }else if(userMode == CommunityService.USER_MODE_HCP){
            parameters = new Map<String, String>{
                    'HCPName' => getFullContactName(cnt),
                    'HCPLanguage' => cnt.Language__c
            };
        }else{
            initParamsFromPE(contactId);
        }
    }
    
    private void initParamsFromUser(Id userId){
        User user = [SELECT Id, ContactId FROM User WHERE Id =: userId];
        initParamsFromContact(user.ContactId);
    }
    
    public String getUserName(){
        String userNameParam = userMode + 'Name';
        return parameters.get(userNameParam);
    }
    
    public String getUserLanguage(){
        String langParam = userMode + 'Language';
        String language = parameters.get(langParam);
        if(language != null) return language;
        return DEFAULT_LANGUAGE;
    }
    
    private void initDummyParams(){
        List<Email_Dummy_Parameter__mdt> mparams = [SELECT Id, Label, Value__c FROM Email_Dummy_Parameter__mdt];
        parameters = new Map<String, String>();
        for(Email_Dummy_Parameter__mdt mparam : mparams) parameters.put(mparam.Label, mparam.Value__c);
    }
    
    private void initDelegates(Contact cnt) {
        //delegated by PI
        List<Site_Staff__c> siteStaffs = [
                SELECT toLabel(Delegate_Level__c),
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                        Study_Site__r.Clinical_Trial_Profile__r.Official_Title__c
                FROM Site_Staff__c
                WHERE Site_Contact__c = :cnt.Id
        ];
        TranslateHelper.translate(siteStaffs, cnt.Language__c);
        for (Site_Staff__c PIDelegate : siteStaffs) {
            DelegateLevelWrapper dlw = new DelegateLevelWrapper();
            dlw.level = PIDelegate.Delegate_Level__c;
            dlw.studyName = PIDelegate.Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c;
            delegateLevelsPI.add(dlw);
        }
        delegateLevelsPI.sort();
        
        //delegated by HCP
        List<Referring_HCP_Staff__c> hcpStaffs = [
                SELECT toLabel(Delegate_Level__c),
                        HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__r.Study_Title__c,
                        HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c,
                        HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__r.Official_Title__c
                FROM Referring_HCP_Staff__c
                WHERE Contact__c = :cnt.Id
        ];
        TranslateHelper.translate(hcpStaffs, cnt.Language__c);
        for (Referring_HCP_Staff__c HCPDelegate : hcpStaffs) {
            DelegateLevelWrapper dlw = new DelegateLevelWrapper();
            dlw.level = HCPDelegate.Delegate_Level__c;
            dlw.studyName = HCPDelegate.HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__r.Study_Code_Name__c;
            delegateLevelsHCP.add(dlw);
        }
        delegateLevelsHCP.sort();
    }
    
    private String getFullContactName(Contact c){
        String fullName = c.Name;
        if(c.Salutation != null) fullName = c.Salutation + ' ' + fullName;
        return fullName;
    }
    
    private String getFullParticipantName(Participant__c participant){
        List<String> nameParts = new List<String>();
        if(participant.First_Name__c != null) nameParts.add(participant.First_Name__c);
        if(participant.Last_Name__c != null) nameParts.add(participant.Last_Name__c);
        return String.join(nameParts, ' ');
    }
    
    private String getParticipantLanguage(Participant__c participant){
        String participantLanguage = participant.Contact__r.Language__c;
        if(participant.Contact__c == null) participantLanguage = participant.Language_Preference_Code__c;
        return participantLanguage;
    }
  
}