objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Referring_HCP_Staff__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Referring HCP Staffs</relationshipLabel>
        <relationshipName>Referring_HCP_Staffs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Delegate_Level__c</fullName>
        <label>Delegate Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCP_Enrollment__c</fullName>
        <label>HCP Enrollment</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Referring HCP Staffs</relationshipLabel>
        <relationshipName>Referring_HCP_Staffs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Referring HCP Staff</label>
    <nameField>
        <displayFormat>HCPS-{000000}</displayFormat>
        <label>Referring HCP Staff Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referring HCP Staffs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Site_Staff__c.object
<CustomObject>
    <description>Used to connect Contacts with Study Sites to represent a Principal Investigator&apos;s team</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; Study_Site__r.Clinical_Trial_Profile__c,  Study_Site__r.Clinical_Trial_Profile__r.Name )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Clinical Trial Profile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delegate_Level__c</fullName>
        <label>Delegate Level</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Level 1</fullName>
                </value>
                <value>
                    <fullName>Level 2</fullName>
                </value>
                <value>
                    <fullName>Level 3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site_Contact__c</fullName>
        <label>Site Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Staff&apos;s Study Sites</relationshipLabel>
        <relationshipName>PI_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Site Staff</relationshipLabel>
        <relationshipName>Site_Staff</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Site Staff</label>
    <nameField>
        <displayFormat>Staff #{0000}</displayFormat>
        <label>Site Staff</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Staff</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DelegateService.cls
/**
 * Created by Leonid Bartenev
 */

public class DelegateService {
    
    public static String OWNER_LEVEL = 'All';
    public static String DELEGATE_LEVEL_1 = 'Level 1';
    public static String DELEGATE_LEVEL_2 = 'Level 2';
    public static String DELEGATE_LEVEL_3 = 'Level 3';

    public static final List<String> DELEGATE_LEVEL_1_AND_LOW = new List<String>{
            DELEGATE_LEVEL_1,
            DELEGATE_LEVEL_2,
            DELEGATE_LEVEL_3
    };
    public static final List<String> DELEGATE_LEVEL_2_AND_LOW = new List<String>{
            DELEGATE_LEVEL_2,
            DELEGATE_LEVEL_3
    };


    private static Map<Id, String> piStudySitesAccessLevelMap;
    private static Map<Id, String> hcpEnrollmentsAccessLevelMap;
    private static Map<Id, String> piStudiesAccessLevel;
    private static Map<Id, String> hcpStudiesAccessLevel;
    private static Map<Id, Id> studyPIContactsMap;
    private static Map<Id, Id> studyHCPContactsMap;
    private static Map<Id, Map<Id,Site_Staff__c>> piTeamStaffTrialMap;
    private static Map<Id, Map<Id,Referring_HCP_Staff__c>> hcpTeamStaffTrialMap;
    
    public static final String ACCESS_LEVEL_ALL = 'All';
    
    public static Map<Id, String> getPIStudySitesAccessLevelMap(){
        if(piStudySitesAccessLevelMap == null) init();
        return piStudySitesAccessLevelMap;
    }
    
    public static Map<Id, String> getHCPEnrollmentAccessLevelMap(){
        if(hcpEnrollmentsAccessLevelMap == null) init();
        return hcpEnrollmentsAccessLevelMap;
    }
    
    public static List<Id> getDelegatedHCPEnrollmentIds(){
        return new List<Id>(getHCPEnrollmentAccessLevelMap().keySet());
    }
    
    public static List<Id> getDelegatedStudySiteIds(){
        return new List<Id>(getPIStudySitesAccessLevelMap().keySet());
    }
    
    public static Map<Id, Id> getStudyPIContactsMap(){
        if(studyPIContactsMap == null) init();
        return studyPIContactsMap;
    }
    
    public static Map<Id, Id> getStudyHCPContactsMap(){
        if(studyHCPContactsMap == null) init();
        return studyHCPContactsMap;
    }

    public static Map<Id, Map<Id,Site_Staff__c>> getPITeamStaffTrialMap(){
        if(piTeamStaffTrialMap == null) init();
        return piTeamStaffTrialMap;
    }

    public static Map<Id, Map<Id,Referring_HCP_Staff__c>> getHCPTeamStaffTrialMap(){
        if(hcpTeamStaffTrialMap == null) init();
        return hcpTeamStaffTrialMap;
    }
    
    public static Id getContactId(Id studyId, String userMode){
        Id contactId;
        if(userMode == CommunityService.USER_MODE_PI){
            contactId = getStudyPIContactsMap().get(studyId);
        }else if(userMode == CommunityService.USER_MODE_HCP){
            contactId = getStudyHCPContactsMap().get(studyId);
        }
        if(contactId != null) return contactId;
        return CommunityService.getUserContact().Id;
    }
    
    public static Map<Id, String> getStudiesAccessLevelMap(String userMode){
        if(userMode == CommunityService.USER_MODE_PI){
            if(piStudiesAccessLevel == null) init();
            return piStudiesAccessLevel;
        }else{
            if(hcpStudiesAccessLevel == null) init();
            return hcpStudiesAccessLevel;
        }
    }
    
    public static String getStudyAccessLevel(Id studyId, String userMode){
        String accessLevel = getStudiesAccessLevelMap(userMode).get(studyId);
        if(accessLevel != null) return accessLevel;
        return ACCESS_LEVEL_ALL;
    }
    
    public static void init(){
        List<Site_Staff__c> piStaffs = [
                SELECT Id, Study_Site__c,
                        Study_Site__r.Principal_Investigator__c,
                        Study_Site__r.Clinical_Trial_Profile__c,
                        Delegate_Level__c,
                        Site_Contact__c
                FROM Site_Staff__c
                WHERE Site_Contact__c =: CommunityService.getUserContact().Id
                OR Study_Site__r.Principal_Investigator__c =: CommunityService.getUserContact().Id
        ];
        piStudySitesAccessLevelMap = new Map<Id, String>();
        piStudiesAccessLevel = new Map<Id, String>();
        studyPIContactsMap = new Map<Id, Id>();
        piTeamStaffTrialMap = new Map<Id, Map<Id,Site_Staff__c>>();
        for(Site_Staff__c siteStaff : piStaffs) {
            if(siteStaff.Site_Contact__c == CommunityService.getUserContact().Id){
                piStudySitesAccessLevelMap.put(siteStaff.Study_Site__c, siteStaff.Delegate_Level__c);
                piStudiesAccessLevel.put(siteStaff.Study_Site__r.Clinical_Trial_Profile__c, siteStaff.Delegate_Level__c);
                studyPIContactsMap.put(siteStaff.Study_Site__r.Clinical_Trial_Profile__c, siteStaff.Study_Site__r.Principal_Investigator__c);
            }
            if(siteStaff.Study_Site__r.Principal_Investigator__c == CommunityService.getUserContact().Id){
                if(!piTeamStaffTrialMap.containsKey(siteStaff.Site_Contact__c)){
                    piTeamStaffTrialMap.put(siteStaff.Site_Contact__c, new Map<Id,Site_Staff__c>());
                }
                piTeamStaffTrialMap.get(siteStaff.Site_Contact__c).put(siteStaff.Study_Site__c,siteStaff);
            }

        }
    
        List<Referring_HCP_Staff__c> hcpStaffs = [
                SELECT Id, Delegate_Level__c,
                        HCP_Enrollment__r.HCP_Contact__c,
                        HCP_Enrollment__c,
                        HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__c,
                        Contact__c
                FROM Referring_HCP_Staff__c
                WHERE Contact__c =: CommunityService.getUserContact().Id
                OR HCP_Enrollment__r.HCP_Contact__c =: CommunityService.getUserContact().Id
        ];
        hcpEnrollmentsAccessLevelMap = new Map<Id, String>();
        hcpStudiesAccessLevel = new Map<Id, String>();
        studyHCPContactsMap = new Map<Id, Id>();
        hcpTeamStaffTrialMap = new Map<Id, Map<Id, Referring_HCP_Staff__c>>();
        for(Referring_HCP_Staff__c hcpStaff : hcpStaffs) {
            if(hcpStaff.Contact__c == CommunityService.getUserContact().Id){
                hcpEnrollmentsAccessLevelMap.put(hcpStaff.HCP_Enrollment__c, hcpStaff.Delegate_Level__c);
                hcpStudiesAccessLevel.put(hcpStaff.HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__c, hcpStaff.Delegate_Level__c);
                studyHCPContactsMap.put(hcpStaff.HCP_Enrollment__r.Study_Site__r.Clinical_Trial_Profile__c,  hcpStaff.HCP_Enrollment__r.HCP_Contact__c);
            }
            if(hcpStaff.HCP_Enrollment__r.HCP_Contact__c == CommunityService.getUserContact().Id){
                if(!hcpTeamStaffTrialMap.containsKey(hcpStaff.Contact__c)){
                    hcpTeamStaffTrialMap.put(hcpStaff.Contact__c, new Map<Id,Referring_HCP_Staff__c>());
                }
                hcpTeamStaffTrialMap.get(hcpStaff.Contact__c).put(hcpStaff.HCP_Enrollment__c,hcpStaff);
            }
        }
    }

}