objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Official_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Official Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Official Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Orientation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orientation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Recruitment_Status__c</fullName>
        <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
        <label>Override Recruitment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actively Enrolling</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Enrollment Closed</fullName>
                </value>
                <value>
                    <fullName>No_Longer_Enrolling</fullName>
                    <label>No Longer Enrolling</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Sponsor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Study Sponsor&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Sponsor</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>Title of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Title</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Study_Site__r.Site__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudySiteService.cls
/**
 * Created by D.Yasinskyi on 28.03.2018
 */
public without sharing class StudySiteService {
    public final static List<String> PI_STATUS_VALUES = new List<String>();
    public final static String PI_S_INVITATION_SENT = 'Invitation Sent';
    public final static String PI_S_ACCEPTED = 'Accepted';
    public final static String PI_S_ACCEPTED_A = 'Accepted (Admin)';
    public final static String PI_S_NON_RESPONCIVE_A = 'Non-Responsive (Admin)';
    public final static String PI_S_ON_HOLD = 'On Hold';
    public final static String PI_S_ON_HOLD_A = 'On Hold (Admin)';
    public final static String PI_S_DEACTIVATED_A = 'Deactivated (Admin)';
    public final static String PI_S_DECLINED_ACCEPTANCE = 'Declined (Acceptance)';
    //oldStatus/<actionType, newStatus>
    public final static Map<String, Map<String, String>> SS_CHANGE_STATUS_MAP = new Map<String, Map<String, String>>();
    
    public final static List<String> STATUS_GROUP_ACCEPTED = new List<String>{
            PI_S_ACCEPTED,
            PI_S_ACCEPTED_A
    };

    public final static List<String> STATUS_GROUP_ON_HOLD = new List<String>{
            PI_S_ON_HOLD,
            PI_S_ON_HOLD_A
    };

    static {
        for (Schema.PicklistEntry ple : Study_Site__c.Override_PI_Referral_Status__c.getDescribe().getPicklistValues()) {
            PI_STATUS_VALUES.add(ple.getValue());
        }
        SS_CHANGE_STATUS_MAP.put(PI_S_INVITATION_SENT, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.get(PI_S_INVITATION_SENT).put('decline', PI_S_DECLINED_ACCEPTANCE);

        SS_CHANGE_STATUS_MAP.put(PI_S_ACCEPTED, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_ACCEPTED_A, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_NON_RESPONCIVE_A, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_ON_HOLD, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_ON_HOLD_A, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_DEACTIVATED_A, new Map<String, String>());
        SS_CHANGE_STATUS_MAP.put(PI_S_DECLINED_ACCEPTANCE, new Map<String, String>());

    }

    public static String changeStatus(Id studySiteId, String userMod, String newStatusType) {
        Study_Site__c studySite = [
                SELECT Id, Override_PI_Referral_Status__c
                FROM Study_Site__c
                WHERE Id = :studySiteId
        ];

        if (studySite == null) throw new AuraHandledException('Incorrect Study site studySiteId=' + studySiteId);
        String oldStatus = studySite.Override_PI_Referral_Status__c;
        String newStatus = SS_CHANGE_STATUS_MAP.get(oldStatus).get(newStatusType);

        if (newStatus == null) {
            throw new AuraHandledException('Invalid action! Can`t change this status to status = ' + newStatusType);
        }
        studySite.Override_PI_Referral_Status__c = newStatus;
        update studySite;
        return newStatus;
    }

    public static List<Study_Site__c> getStudySitesForPI() {
        return getStudySitesCommon(CommunityService.USER_MODE_PI, null, false);
    }

    private static final List<String> SS_COMMON_FIELDS = new List<String>{
            'Id',
            'Name',
            'Site__c',
            'Override_PI_Referral_Status__c',
            'Clinical_Trial_Profile__c',
            'Clinical_Trial_Profile__r.Id',
            'Clinical_Trial_Profile__r.Study_Title__c',
            'Clinical_Trial_Profile__r.Study_Code_Name__c',
            'Clinical_Trial_Profile__r.Official_Title__c',
            'Clinical_Trial_Profile__r.Study_Sponsor__c',
            'Clinical_Trial_Profile__r.Override_Recruitment_Status__c',
            'Clinical_Trial_Profile__r.Terms_And_Conditions_ID__c',
            'Clinical_Trial_Profile__r.Link_to_Medical_Record_Review__c',
            'Clinical_Trial_Profile__r.Link_to_Pre_screening__c',
            'Clinical_Trial_Profile__r.Orientation_Required__c '
    };

    public static List<Study_Site__c> getStudySitesCommon(String userMode, String filter, Boolean excludeDelegates){
        String query = 'SELECT ' + String.join(SS_COMMON_FIELDS, ',') +
                ' FROM Study_Site__c ' +
                ' WHERE ' + getUserModeFilter(userMode, excludeDelegates);
        if(filter != null) query += ' ' + filter;
        System.debug('EXECUTE QUERY: ' + query);
        List<Study_Site__c> ssList = Database.query(query);
        TranslateHelper.translate(ssList);
        return ssList;
    }

    public static String getUserModeFilter(String userMode, Boolean excludeDelegates){
        String filter = ' Clinical_Trial_Profile__c != NULL ' +
                        ' AND Override_PI_Referral_Status__c != NULL ';
        if(userMode == CommunityService.USER_MODE_PI){
            if(excludeDelegates){
                filter +=       ' AND  Principal_Investigator__c = \'' + CommunityService.getUserContact().Id + '\' ';
            }
            else{
                filter +=       ' AND ( ' +
                        '       Principal_Investigator__c = \'' + CommunityService.getUserContact().Id + '\' ' +
                        '       OR Id IN (\'' + String.join(DelegateService.getDelegatedStudySiteIds(), '\',\'') + '\')'+
                        '   ) ';
            }

        }
        return filter;
    }

    public static Study_Site__c getStudySiteForHCPById(Id ssId){
        List<Study_Site__c> studySites = getStudySitesCommon(
                CommunityService.USER_MODE_HCP,
                ' AND Id = \'' + ssId + '\' ',
                false
        );
        if(studySites.size() == 0) throw new CommunityServiceException('Data not found');
        return studySites[0];
    }

    public static List<Study_Site__c> getStudySiteForPIByTrialId(Id trialId) {
        return getStudySitesCommon(
                CommunityService.USER_MODE_PI,
                ' AND Clinical_Trial_Profile__c = \'' + trialId + '\' ' +
                        ' AND Override_PI_Referral_Status__c != NULL',
                false
        );
    }

    public static List<Study_Site__c> getStudySitesForHCP(List<Id> trialIds) {
        List<HCP_Enrollment__c> hcpEnrollments = HCPEnrollmentService.getHCPEnrollmentsCommon(
                CommunityService.USER_MODE_HCP,
                ' AND Study_Site__r.Clinical_Trial_Profile__c IN (\'' + String.join(trialIds, '\',\'') + '\')',
                false
        );
        List<Study_Site__c> resList = new List<Study_Site__c>();
        for (HCP_Enrollment__c he : hcpEnrollments) resList.add(he.Study_Site__r);
        return resList;
    }

    public static List<Study_Site__c> getStudySitesForHCPByTrialId(Id trialId){
        String query = 'SELECT ' + String.join(SS_COMMON_FIELDS, ',') +
                ' FROM Study_Site__c WHERE Clinical_Trial_Profile__c =\'' + trialId + '\'' +
                '  AND Override_PI_Referral_Status__c != NULL ' +
                '  AND Override_PI_Referral_Status__c IN (\'' + String.join(STATUS_GROUP_ACCEPTED, '\',\'') + '\')';
        return Database.query(query);
    }
}