objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Terms_And_Conditions__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active Portal T&amp;C</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Languages</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Master_Terms_And_Conditions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Terms And Conditions</relationshipLabel>
        <relationshipName>Terms_And_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>T_C_Text__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>T&amp;C Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Terms And Conditions</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Terms And Conditions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Terms_And_Conditions_Acceptance__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Accepted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Terms And Conditions Acceptance</relationshipLabel>
        <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Terms_And_Conditions_Acceptance</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Terms And Conditions Acceptance</label>
    <nameField>
        <displayFormat>TCA-{000000}</displayFormat>
        <label>Terms And Conditions Acceptance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms And Conditions Acceptance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TermsAndConditions.cls
global without sharing class TermsAndConditions {

    public static Terms_And_Conditions__c getPortalTC(){
        return getTC(null, null);
    }
    
    public static Terms_And_Conditions__c getTrialTC(Id ctpId){
        Clinical_Trial_Profile__c [] ctpList = [
                SELECT Terms_And_Conditions_ID__c
                FROM Clinical_Trial_Profile__c
                WHERE Id =: ctpId
        ];
        if(ctpList.size() > 0) {
            return getTC(ctpList[0].Terms_And_Conditions_ID__c, null);
        }
        return null;
    }
    
    public static Terms_And_Conditions__c getTC(Id tcId, String languageCode){
        if(String.isEmpty(languageCode)) languageCode = UserInfo.getLanguage();
        String query =
                ' SELECT Id, T_C_Text__c, ' +
                '   (SELECT Id, T_C_Text__c FROM Terms_And_Conditions__r WHERE Language__c = \'' + languageCode  + '\') ' +
                ' FROM Terms_And_Conditions__c' +
                ' WHERE ';
        if(tcId != null) {
            query += ' Id =\'' + tcId + '\' ';
        }else{
            query += ' Active__c = TRUE ';
        }
        query += ' ORDER BY Name DESC LIMIT 1';
        System.debug('QUERY: ' + query);
        Terms_And_Conditions__c [] tcList = Database.query(query);
        if(tcList.size() > 0) {
            Terms_And_Conditions__c tc = tcList[0];
            if(tc.Terms_And_Conditions__r.size() > 0) tc.T_C_Text__c = tc.Terms_And_Conditions__r[0].T_C_Text__c;
            return tc;
        }
        return null;
    }
    
    public static Boolean isTCAccepted(Id tcId){
        return getTCA(tcId) != null;
    }

    public static Map<Id, Boolean> getTrialsAcceptanceMap(List<Clinical_Trial_Profile__c> trials){
        List<Id> tcIds = new List<Id>();
        for(Clinical_Trial_Profile__c trial : trials) if(trial.Terms_And_Conditions_ID__c != null) tcIds.add(trial.Terms_And_Conditions_ID__c);
        List<Terms_And_Conditions_Acceptance__c> tcAcceptances = [
                SELECT Id, Terms_And_Conditions__c
                FROM Terms_And_Conditions_Acceptance__c
                WHERE Terms_And_Conditions__c IN: tcIds AND User__c =: UserInfo.getUserId()
        ];
        //Map tcId -> tcaId
        Map<Id, Id> tcaMap = new Map<Id, Id>();
        for(Terms_And_Conditions_Acceptance__c tca : tcAcceptances){
            tcaMap.put(tca.Terms_And_Conditions__c, tca.Id);
        }
        Map<Id, Boolean> resMap = new Map<Id, Boolean>();
        for(Clinical_Trial_Profile__c trial : trials){
            if(trial.Terms_And_Conditions_ID__c != null){
                resMap.put(trial.Id, tcaMap.get(trial.Terms_And_Conditions_ID__c) != null);
            }
        }
        return resMap;
    }

    public static Terms_And_Conditions_Acceptance__c getTCA(Id tcId){
        List<Terms_And_Conditions_Acceptance__c> tcAcceptance = [
                SELECT Id, Accepted_Date__c
                FROM Terms_And_Conditions_Acceptance__c
                WHERE User__c =: UserInfo.getUserId() AND Terms_And_Conditions__c =: tcId
        ];
        if(tcAcceptance.size() > 0) return tcAcceptance[0];
        return null;

    }

    public static void acceptTC(Id tcId){
        if(!isTCAccepted(tcId)){
            Terms_And_Conditions_Acceptance__c tca = new Terms_And_Conditions_Acceptance__c(
                    Accepted_Date__c = Datetime.now(),
                    Terms_And_Conditions__c = tcId,
                    User__c = UserInfo.getUserId()
            );
            insert tca;
        }
    }

}