objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>NCT_Number__c</fullName>
        <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
        <label>NCT Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <description>QI assigned unique ID for a study</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
        <label>Protocol ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>Title of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Title</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>userCommunityMode__c</fullName>
        <description>Current view point for Community</description>
        <label>User Community Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>userCommunytyType__c</fullName>
        <description>User types for community - HCP / PI / Participant</description>
        <inlineHelpText>Select user types for community</inlineHelpText>
        <label>User Community Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Clinical Trial Profile&apos;s Protocol Id</inlineHelpText>
        <label>Protocol ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site_Key__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Study Site Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_CommunityUserOnStudySite.cls
/**
 * Created by Leonid Bartenev
 */

@IsTest
private class Test_CommunityUserOnStudySite {


    static testMethod void test1() {
        Account acc1 = new Account(
                Name = 'newAcc1'
        );
        insert acc1; 

        Contact piContact = new Contact(
                AccountId = acc1.Id,
                LastName = 'portalTestUser1',
                Email = 'some@email.com'
        );
        insert piContact;



        Clinical_Trial_Profile__c clinicalTrialProfile = new Clinical_Trial_Profile__c(
                Protocol_ID__c = 'test protocol Id',
                Study_Title__c = 'Test Study',
                Study_Code_Name__c = 'Test Study Code Name',
                NCT_Number__c = 'NCT00000000'
        );
        insert clinicalTrialProfile;

        Study_Site__c studySite = new Study_Site__c(
                Name = 'Test Study 2',
                Clinical_Trial_Profile__c = clinicalTrialProfile.Id,
                Site__c = acc1.Id,
                Principal_Investigator__c = piContact.Id
        );
        insert studySite;

        Contact piContact1 = [SELECT userCommunityMode__c, userCommunytyType__c FROM Contact WHERE Id =: piContact.Id];
        System.assertEquals('PI', piContact1.userCommunityMode__c);
        System.assertEquals(true, piContact1.userCommunytyType__c.contains('PI'));

        piContact1.userCommunytyType__c = 'HCP';
        update piContact1;

        Account acc2 = new Account(
                Name = 'newAcc2'
        );
        insert acc2;

        Study_Site__c studySite2 = new Study_Site__c(
                Name = 'Test Study 3',
                Clinical_Trial_Profile__c = clinicalTrialProfile.Id,
                Site__c = acc2.Id,
                Study_Site_Key__c = '111',
                Principal_Investigator__c = piContact.Id
        );
        insert studySite2;

        Contact piContact2 = [SELECT userCommunityMode__c, userCommunytyType__c FROM Contact WHERE Id =: piContact.Id];    
        System.assertEquals(true, piContact2.userCommunytyType__c.contains('PI'));
    }

 }