objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Orientation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orientation Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <label>HCP Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HCP&apos;s Study Sites</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP_Contact__c</fullName>
        <formula>HYPERLINK(&quot;/&quot;&amp; HCP__r.HCP_Contact__c ,HCP__r.HCP_Contact__r.FirstName&amp;&quot; &quot;&amp;  HCP__r.HCP_Contact__r.LastName )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>HCP Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Principal_Investigator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Principal Investigator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PI&apos;s Study Sites</relationshipLabel>
        <relationshipName>Study_Site</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ExcelController.cls
public class ExcelController {
    
    private String userMode;
    private String study;
    private String referringClinic;
    private String dateRange;
    
    private List<String> peFields;
    private List<FieldSetMember> peFSMList;
    private List<String> hcpeFields;
    private List<FieldSetMember> hcpeFSMList;
    
    private static final List<String> USER_MODES_FOR_REPORTS = new List<String>{
            CommunityService.USER_MODE_PI,
            CommunityService.USER_MODE_HCP
    };
    
    public ExcelController() {
        //userMode = CommunityService.USER_MODE_HCP;
        //CommunityService.setDummyUserContact('0030n00000d8PgE');
        if(ApexPages.currentPage() != null){
            userMode = ApexPages.currentPage().getParameters().get('userMode');
            study = ApexPages.currentPage().getParameters().get('study');
            referringClinic = ApexPages.currentPage().getParameters().get('referringClinic');
            dateRange = ApexPages.currentPage().getParameters().get('dateRange');
        }
        peFields = new List<String>();
        peFSMList = SObjectType.Participant_Enrollment__c.FieldSets.ExportExcel.getFields();
        for (Schema.FieldSetMember fsm : peFSMList) {
            peFields.add(fsm.getFieldPath());
        }
        hcpeFields = new List<String>();
        hcpeFSMList = SObjectType.HCP_Enrollment__c.FieldSets.ExportExcel.getFields();
        for (Schema.FieldSetMember flds : hcpeFSMList) {
            hcpeFields.add(flds.getFieldPath());
        }

    }

    public List<Participant_Enrollment__c> getPEList() {
        if(!USER_MODES_FOR_REPORTS.contains(userMode)) return new List<Participant_Enrollment__c>();
        
        String filter;
        List<String> filters = new List<String>();
        if (!String.isBlank(study)) filters.add(' Study_Site__r.Clinical_Trial_Profile__c = \'' + study + '\' ');
        if (!String.isBlank(referringClinic)) filters.add(' HCP__r.HCP_Contact__r.AccountId = \'' + referringClinic + '\' ');
        if (!String.isEmpty(dateRange)) filters.add(' CreatedDate ' + EncodingUtil.urlDecode(dateRange, 'UTF-8'));
        if (!filters.isEmpty()) filter = 'AND ' + String.join(filters, ' AND ');
        
        System.debug('FILTER: ' + filter);
        return ParticipantEnrollmentService.getPEnrolmentsCommonCustomFields(userMode, peFields, filter);
    }

    public List<HCP_Enrollment__c> getHCPEList(){
        if(!USER_MODES_FOR_REPORTS.contains(userMode)) return new List<HCP_Enrollment__c>();
        
        String filter;
        List<String> filters = new List<String>();
        filters.add('Study_Site__r.Clinical_Trial_Profile__r.Orientation_Required__c = true');
        if (!String.isEmpty(study)) filters.add(' Study_Site__r.Clinical_Trial_Profile__c = \'' + study + '\' ');
        if (!String.isEmpty(referringClinic)) filters.add(' HCP_Contact__r.AccountId = \'' + referringClinic + '\' ');
        if (!String.isEmpty(dateRange)) filters.add(' CreatedDate ' + EncodingUtil.urlDecode(dateRange, 'UTF-8'));
        if (!filters.isEmpty()) filter = 'AND ' + String.join(filters, ' AND ');
        
        System.debug('FILTER: ' + filter);
        return HCPEnrollmentService.getHCPEnrollmentsCommonCustomFields(userMode, hcpeFields, filter, false);
    }
    
}