objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HCP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/StudyActionsPI.cls
/**
 * Created by Leonid Bartenev
 */

public class StudyActionsPI extends StudyActions{
    
    public StudyActionsPI(Study_Site__c studySite){
        this(
                studySite.Clinical_Trial_Profile__r,
                studySite,
                null,
                null
        );
    }
    
    public StudyActionsPI(HCP_Enrollment__c hcpEnrollment){
        this(
                hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r,
                hcpEnrollment.Study_Site__r,
                hcpEnrollment,
                null
        );
    }
    
    public StudyActionsPI(Participant_Enrollment__c pe){
        this(
                pe.Study_Site__r.Clinical_Trial_Profile__r,
                pe.Study_Site__r,
                pe.HCP__r,
                pe
        );
    }
    
    public StudyActionsPI(Clinical_Trial_Profile__c study, Study_Site__c studySite, HCP_Enrollment__c hcpEnrollment, Participant_Enrollment__c pe){
        super(study,studySite, hcpEnrollment, CommunityService.USER_MODE_PI);
    
        //init reasons:
        List<String> manageReferralsStatuses = new List<String>{
                StudySiteService.PI_S_ACCEPTED,
                StudySiteService.PI_S_ACCEPTED_A,
                StudySiteService.PI_S_ON_HOLD,
                StudySiteService.PI_S_ON_HOLD_A
        };
        
        DisableReason manageReferralsStatusesReason = new DisableReason(
                !manageReferralsStatuses.contains(studySite.Override_PI_Referral_Status__c),
                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_SS_STATUS
        );
        
        DisableReason delegateL3CannotAccept = new DisableReason(
                studyAccessLevel == DelegateService.DELEGATE_LEVEL_3 && pe != null &&
                        pe.Participant_Status__c.contains('Referral') && !pe.Participant_Status__c.contains('Accepted'),
                REASON_LABEL_ACTION_NOT_ALLOWED_ON_ACCESS_LEVEL
        );


        //init actions:
        actions.put(ACT_MANAGE_REFERRALS, new Action(
                ACT_MANAGE_REFERRALS,
                LABEL_MANAGE_REFERRALS,
                'referrals',
                new List<DisableReason>{
                        studyNoLongerEnrollingReason,
                        manageReferralsStatusesReason
                }
        ));
        actions.put(ACT_MANAGE_REFERRING_CLINICS, new Action(
                ACT_MANAGE_REFERRING_CLINICS,
                LABEL_MANAGE_REFERRING_CLINICS,
                'referring-clinic',
                new List<DisableReason>{
                        studyNoLongerEnrollingReason,
                        manageReferralsStatusesReason
                }
        ));
        actions.put(ACT_CHANGE_PE_STATUS_BY_PI, new Action(
                ACT_CHANGE_PE_STATUS_BY_PI,
                null,
                null,
                new List<DisableReason>{
                        delegateL3CannotAccept,
                        hcpOnHoldReason,
                        studySiteOnHoldReason,
                        hcpNotActiveReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                }
        ));
    
        actions.put(ACT_HCP_ACTIVATE, new Action(
                ACT_HCP_ACTIVATE,
                LABEL_HCP_ACTIVATE,
                null,
                new List<DisableReason>{
                        level2AndLowReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'green'
        ));
        actions.put(ACT_HCP_APPROVE, new Action(
                ACT_HCP_APPROVE,
                LABEL_HCP_APPROVE,
                null,
                new List<DisableReason>{
                        level2AndLowReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'green'
        ));
        actions.put(ACT_HCP_ORIENTATION_ATTENDED_AND_ACTIVATE, new Action(
                ACT_HCP_ORIENTATION_ATTENDED_AND_ACTIVATE,
                LABEL_HCP_ORIENTATION_ATTENDED_AND_ACTIVATE,
                null,
                new List<DisableReason>{
                        level2AndLowReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'green'
        ));
        actions.put(ACT_HCP_DECLINE, new Action(
                ACT_HCP_DECLINE,
                LABEL_HCP_DECLINE,
                null,
                new List<DisableReason>{
                        level2AndLowReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'red'
        ));
        actions.put(ACT_HCP_DEACTIVATE, new Action(
                ACT_HCP_DEACTIVATE,
                LABEL_HCP_DEACTIVATE,
                null,
                new List<DisableReason>{
                        supportLevelReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'red'
        ));
        actions.put(ACT_HCP_ON_HOLD, new Action(
                ACT_HCP_ON_HOLD,
                LABEL_HCP_ON_HOLD,
                null,
                new List<DisableReason>{
                        level2AndLowReason,
                        hcpLockedByAdmin,
                        studySiteOnHoldReason,
                        studySiteNotAcceptedReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason
                },
                'orange'
        ));
        
        List<String> openToReceiveReferralsStatuses = new List<String>{
                StudySiteService.PI_S_INVITATION_SENT,
                StudySiteService.PI_S_DECLINED_ACCEPTANCE,
                StudySiteService.PI_S_NON_RESPONCIVE_A
        };
        
        actions.put(ACT_OPEN_TO_RECEIVE_REFERRALS, new Action(
                ACT_OPEN_TO_RECEIVE_REFERRALS,
                LABEL_OPEN_TO_RECEIVE_REFERRALS,
                'check-in-square-cut',
                new List<DisableReason>{
                        level1AndLowReason,
                        studyNoLongerEnrollingReason,
                        tcAcceptanceRequiredReason,
                        new DisableReason(
                                !openToReceiveReferralsStatuses.contains(studySite.Override_PI_Referral_Status__c),
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_SS_STATUS
                        )
                },
                'primary'
        ));
    
        actions.put(ACT_NO_THANKS, new Action(
                ACT_NO_THANKS,
                LABEL_NO_THANKS,
                'icon-disabled',
                new List<DisableReason>{
                        studyNoLongerEnrollingReason,
                        new DisableReason(
                                studySite.Override_PI_Referral_Status__c != StudySiteService.PI_S_INVITATION_SENT,
                                REASON_LABEL_NOT_ALLOWED_FOR_CURRENT_SS_STATUS
                        )
                },
                'secondary'
        ));
        
        //init study item actions list
        if(manageReferralsStatuses.contains(studySite.Override_PI_Referral_Status__c)){
            studyListViewItemActions.add(actions.get(ACT_MANAGE_REFERRALS));
            studyListViewItemActions.add(actions.get(ACT_MANAGE_REFERRING_CLINICS));
        }
        
        if(openToReceiveReferralsStatuses.contains(studySite.Override_PI_Referral_Status__c)){
            if(isTCAcceptanceRequired){
                studyListViewItemActions.add(actions.get(ACT_VIEW_TC));
            }else{
                studyListViewItemActions.add(actions.get(ACT_OPEN_TO_RECEIVE_REFERRALS));
            }
        }
        if(studySite.Override_PI_Referral_Status__c == StudySiteService.PI_S_INVITATION_SENT){
            studyListViewItemActions.add(actions.get(ACT_NO_THANKS));
        }
        
        //prepare bottom bar actions:
        if(openToReceiveReferralsStatuses.contains(studySite.Override_PI_Referral_Status__c)){
            if(isTCAcceptanceRequired){
                studyDetailBottomBarActions.add(actions.get(ACT_VIEW_TC));
            }else{
                studyDetailBottomBarActions.add(actions.get(ACT_OPEN_TO_RECEIVE_REFERRALS));
            }
            if(studySite.Override_PI_Referral_Status__c == StudySiteService.PI_S_INVITATION_SENT){
                studyDetailBottomBarActions.add(actions.get(ACT_NO_THANKS));
            
            }
        }
        
        //prepare study detail actions list:
        if(study.Terms_And_Conditions_ID__c != null) studyDetailActions.add(actions.get(ACT_VIEW_TC));
    
    
      
    }

}