objects/Clinical_Trial_Profile__c.object
<CustomObject>
    <description>All clinical trial details which exist at clinicaltrials.gov, with additional metadata describing the inclusion / exclusion criteria, and identification of which clinical trials are awarded to QuintilesIMS</description>
    <fields>
        <fullName>Brief_Summary__c</fullName>
        <description>Summary of Title</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Summary&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Brief Summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Condition_s_Therapeutic_Area__c</fullName>
        <description>Therapeutic Area</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Condition&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Condition(s) Therapeutic Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detailed_Description__c</fullName>
        <description>Study Detail Description</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Detailed Description&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Detailed Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Enrolled_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrolled End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interventions__c</fullName>
        <description>A process or action that is the focus of a clinical study.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Intervention&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Interventions</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Link_to_Medical_Record_Review__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires medical record review.</inlineHelpText>
        <label>Link to Medical Record Review</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Link_to_Pre_screening__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Unique URL generated by Survey Gizmo created by SPNL in collaboration with IQVIA Digital Media.  This field must be populated if the study requires pre-screening.</inlineHelpText>
        <label>Link to Pre-screening</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>NCT_Number__c</fullName>
        <description>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>A unique identification code given to each clinical study registered on ClinicalTrials.gov. The format is &quot;NCT&quot; followed by an 8-digit number</inlineHelpText>
        <label>NCT Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Official_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Official Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Official Title</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Orientation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Orientation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Override_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>If populated, this will be the description seen within the community by PIs, HCPs, Participants, etc. describing the clinical study.  This will &quot;override&quot; display of the &quot;Detailed Description&quot; if &quot;Override Description&quot; is populated.</inlineHelpText>
        <label>Override Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Override_Exclusion_Criteria__c</fullName>
        <description>Friendly description of exclusion criteria for use in internal portal</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Override Exclusion Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Override_Inclusion_Criteria__c</fullName>
        <description>Friendly description for internal use</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Override Inclusion Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Override_Recruitment_Status__c</fullName>
        <inlineHelpText>Ability for SPNL or Admins to override the recruiting status of a clinical study.</inlineHelpText>
        <label>Override Recruitment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Actively Enrolling</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Enrollment Closed</fullName>
                </value>
                <value>
                    <fullName>No_Longer_Enrolling</fullName>
                    <label>No Longer Enrolling</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <description>QI assigned unique ID for a study</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Protocol ID = Protocol Number. This is a unique number assigned by the sponsor providing a standard way to identify the study.  Obtain the protocol number from the Project Lead, Clinical Lead, Patient Recruitment Lead, or Site and Patient Networks Lead.</inlineHelpText>
        <label>Protocol ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Sponsor_Pays_for_Referral_Activity__c</fullName>
        <inlineHelpText>Sponsor Pays for Referral Activity</inlineHelpText>
        <label>Sponsor Pays for Referral Activity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Y_N_Unknown</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Code_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Code Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Study_Phase__c</fullName>
        <description>Current Phase of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Study Phase&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Phase</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Study_Sponsor__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Study Sponsor&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Sponsor</label>
        <length>400</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Title__c</fullName>
        <description>Title of the Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Brief Title&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Title</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <description>Type of Study</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This field should map to the &quot;Study Type&quot; field in clinicaltrials.gov</inlineHelpText>
        <label>Study Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Terms And Conditions</label>
        <referenceTo>Terms_And_Conditions__c</referenceTo>
        <relationshipLabel>Clinical Trial Profiles</relationshipLabel>
        <relationshipName>Clinical_Trial_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Clinical Trial Profile</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Clinical Trial Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clinical Trial Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipLabel>HCP Enrollments</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Clinical_Trial_Profile__c</fullName>
        <description>Connects the study site to the primary study that it relates to</description>
        <label>Clinical Trial Profile</label>
        <referenceTo>Clinical_Trial_Profile__c</referenceTo>
        <relationshipName>Study_Site_Profiles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>HCP/Physician Enrollment Start Date</inlineHelpText>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Protocol_ID__c</fullName>
        <formula>Clinical_Trial_Profile__r.Protocol_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Clinical Trial Profile&apos;s Protocol Id</inlineHelpText>
        <label>Protocol ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Pays_for_Referral_Activity__c</fullName>
        <formula>TEXT(Clinical_Trial_Profile__r.Sponsor_Pays_for_Referral_Activity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sponsor Pays for Referral Activity</label>
        <type>Text</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TrialService.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class TrialService {
    
    public static final String STATUS_ACTIVELY_ENROLLING = 'Actively Enrolling';
    public static final String STATUS_NO_LONGER_ENROLLING = 'No Longer Enrolling';

    public static List<Clinical_Trial_Profile__c> getAvailableTrials(String mode){
        Set<Clinical_Trial_Profile__c> trials= new Set<Clinical_Trial_Profile__c>();
        if(mode == CommunityService.USER_MODE_PI){
            List<Study_Site__c> studySites = StudySiteService.getStudySitesCommon(CommunityService.USER_MODE_PI, null, false);
            for(Study_Site__c ss : studySites) trials.add(ss.Clinical_Trial_Profile__r);
        }else if(mode == CommunityService.USER_MODE_HCP){
            List<HCP_Enrollment__c> hcpEnrollments = HCPEnrollmentService.getHCPEnrollmentsCommon(mode, null, false);
            for(HCP_Enrollment__c hcpEnrollment : hcpEnrollments) {
                if(hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r != null) trials.add(hcpEnrollment.Study_Site__r.Clinical_Trial_Profile__r);
            }
        }
        return new List<Clinical_Trial_Profile__c>(trials);
    }
    
    public static List<Clinical_Trial_Profile__c> getOwnTrials(String userMode){
        List<Clinical_Trial_Profile__c> ownTrials = new List<Clinical_Trial_Profile__c>();
        for(Clinical_Trial_Profile__c trial : getAvailableTrials(userMode)){
            if(DelegateService.getStudyAccessLevel(trial.Id, userMode) == DelegateService.OWNER_LEVEL){
                ownTrials.add(trial);
            }
        }
        return ownTrials;
    }

    public static List<Id> getAvailableTrialIds(String mode){
        List<Clinical_Trial_Profile__c> trials = getAvailableTrials(mode);
        List<Id> trialIds = new List<Id>();
        for(Clinical_Trial_Profile__c trial : trials) trialIds.add(trial.Id);
        return trialIds;
    }

    public static Clinical_Trial_Profile__c getTrial(Id trialId){
        List<Clinical_Trial_Profile__c> trials = [
                SELECT Id, Orientation_Required__c,
                        Name,
                        Terms_And_Conditions_ID__c,
                        Study_Sponsor__c,
                        Study_Type__c,
                        Detailed_Description__c,
                        toLabel(Override_Recruitment_Status__c),
                        Brief_Summary__c,
                        Override_Description__c,
                        Override_Inclusion_Criteria__c,
                        Override_Exclusion_Criteria__c,
                        Condition_s_Therapeutic_Area__c,
                        Sponsor_Pays_for_Referral_Activity__c,
                        Study_Phase__c, NCT_Number__c,
                        Protocol_ID__c,
                        Enrollment_Start_Date__c,
                        Enrolled_End_Date__c,
                        Link_to_Medical_Record_Review__c,
                        Link_to_Pre_screening__c,
                        Study_Title__c,
                        Study_Code_Name__c,
                        Official_Title__c,
                        Interventions__c
                FROM Clinical_Trial_Profile__c
                WHERE Id =: trialId
        ];
        if(trials.size() == 0) throw new CommunityServiceException('Data not found');
        TranslateHelper.translate(trials[0]);
        return trials[0];
    }

    public static Boolean isTrialAvailable(Id trialId, String userMode){
        return getAvailableTrialIds(userMode).contains(trialId);
    }

}