objects/Contact.object
<CustomObject>
    <fields>
        <fullName>HCP_DelegateAccessLevel__c</fullName>
        <description>Access level for HCP delegate</description>
        <label>HCP Delegate Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All of same responsibilities. But can&apos;t delegate to others</fullName>
                </value>
                <value>
                    <fullName>All, except referring a patient or delegate to others</fullName>
                </value>
                <value>
                    <fullName>Support Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PI_DelegateAccessLevel__c</fullName>
        <description>Access level for PI delegate</description>
        <label>PI Delegate Access Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All of same responsibilities. But can&apos;t delegate to others</fullName>
                </value>
                <value>
                    <fullName>All, except accepting HCP or delegate to others</fullName>
                </value>
                <value>
                    <fullName>Support Level</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>primaryContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary contact of a delegate</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Delegates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>userCommunityMode__c</fullName>
        <description>Current view point for Community</description>
        <label>User Community Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>userCommunytyType__c</fullName>
        <description>User types for community - HCP / PI / Participant</description>
        <inlineHelpText>Select user types for community</inlineHelpText>
        <label>User Community Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HCP</fullName>
                </value>
                <value>
                    <fullName>PI</fullName>
                </value>
                <value>
                    <fullName>Participant</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MyTeamItemController.cls
/**
 * Created by D.Yasinskyi on 04.05.2018
 */
public without sharing class MyTeamItemController {

    //TODO DEPRECATED CLASS!!!

//    @AuraEnabled
//    public static void changeDelegateAccessLevel(String delegateContactId, String newAccessLevel, String userMode) {
//
//        Contact delegate = getDelegate(delegateContactId);
//
//        if(userMode == CommunityService.USER_MODE_HCP){
//            delegate.HCP_DelegateAccessLevel__c = newAccessLevel;
//        } else if(userMode == CommunityService.USER_MODE_PI){
//            delegate.PI_DelegateAccessLevel__c = newAccessLevel;
//        } else {
//            throw new AuraHandledException('Incorrect User rights!');
//        }
//
//        try {
//            update delegate;
//        } catch (Exception e) {
//            throw new AuraHandledException('Can`t change delegate access level!' + e.getMessage() + '\n' + e.getStackTraceString());
//        }
//    }
//
//    @AuraEnabled
//    public static String removeDelegate(String delegateContactId, String userMode) {
//
//        Contact delegate = getDelegate(delegateContactId);
//        Boolean deleteDelegate = false;
//        String response = 'Delegate ' + delegate.FirstName + ' ' + delegate.LastName;
//
//        if(userMode == CommunityService.USER_MODE_PI){
//            delegate.PI_DelegateAccessLevel__c = null;
//            if(delegate.HCP_DelegateAccessLevel__c == null) deleteDelegate = true;
//        } else if(userMode == CommunityService.USER_MODE_HCP){
//            delegate.HCP_DelegateAccessLevel__c = null;
//            if(delegate.PI_DelegateAccessLevel__c == null) deleteDelegate = true;
//        } else {
//            throw new AuraHandledException('Can`t remove delegate!');
//        }
//
//        if(deleteDelegate){
//            delegate.primaryContact__c = null;
//            delegate.userCommunytyType__c = null;
//            delegate.userCommunityMode__c = null;
//            response += ' was successfully removed!';
//        } else {
//            response += ' access rights was successfully removed!';
//        }
//        try {
//            update delegate;
//            return response;
//        } catch (Exception e) {
//            throw new AuraHandledException('Can`t remove delegate!');
//        }
//    }
//
//    private static Contact getDelegate(String delegateContactId) {
//
//        List<Contact> delegate = [
//                SELECT Id
//                        , FirstName
//                        , LastName
//                        , primaryContact__c
//                        , HCP_DelegateAccessLevel__c
//                        , PI_DelegateAccessLevel__c
//                FROM Contact
//                WHERE Id = :delegateContactId
//                AND primaryContact__c IN (
//                        SELECT ContactId
//                        FROM User
//                        WHERE Id = :UserInfo.getUserId()
//                )
//        ];
//
//        if (delegate.isEmpty()) throw new AuraHandledException('No rights to remove delegate!');
//
//        return delegate[0];
//    }
}