objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>HCP Status per clinical trial by PI</description>
        <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
        <label>HCP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>On Hold (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending Orientation</fullName>
                </value>
                <value>
                    <fullName>Declined (Approval)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Approval)</fullName>
                </value>
                <value>
                    <fullName>Declined (Activation)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Activation)</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Activated (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Admin)</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Status_History__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <description>Status has been changed.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>HCP_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCP Enrollment</label>
        <referenceTo>HCP_Enrollment__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>StatusHistory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewStatus__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>New Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudySite__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Status History</relationshipLabel>
        <relationshipName>Status_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Status History</label>
    <nameField>
        <displayFormat>SH-{0000000}</displayFormat>
        <label>Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Status History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InfoModalController.cls
/**
 * Created by D.Yasinskyi on 01.06.2018
 */
public without sharing class InfoModalController {

    @AuraEnabled
    public static String getHCPEnrollmentHistory(Id HSPEnrollmentId) {

        List<Status_History__c> enrollmentStatusHistories = [
                SELECT Id
                        , Date__c
                        , NewStatus__c
                        , CreatedDate
                        , CreatedBy.FirstName
                        , CreatedBy.LastName
                FROM Status_History__c
                WHERE HCP_Enrollment__c = :HSPEnrollmentId
                ORDER BY CreatedDate DESC
        ];
        for(Status_History__c hist : enrollmentStatusHistories){
            hist.NewStatus__c = TranslateHelper.getPickListLabel(HCP_Enrollment__c.Status__c,hist.NewStatus__c);
        }
        return JSON.serialize(enrollmentStatusHistories);
    }

    @AuraEnabled
    public static String getStudySiteHistory(Id StudySiteId) {

        List<Status_History__c> studySiteStatusHistories = [
                SELECT Id
                        , Date__c
                        , NewStatus__c
                        , CreatedDate
                        , CreatedBy.FirstName
                        , CreatedBy.LastName
                FROM Status_History__c
                WHERE StudySite__c = :StudySiteId
                ORDER BY CreatedDate DESC
        ];

        for(Status_History__c hist : studySiteStatusHistories){
            hist.NewStatus__c = TranslateHelper.getPickListLabel(Study_Site__c.Override_PI_Referral_Status__c,hist.NewStatus__c);
        }

        return JSON.serialize(studySiteStatusHistories);
    }
}