objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Site__c</fullName>
        <formula>Study_Site__r.Site__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Site</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>HCP Status per clinical trial by PI</description>
        <inlineHelpText>HCP Status per clinical trial by PI</inlineHelpText>
        <label>HCP Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>On Hold (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Approval Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending</fullName>
                </value>
                <value>
                    <fullName>Activation Pending Orientation</fullName>
                </value>
                <value>
                    <fullName>Declined (Approval)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Approval)</fullName>
                </value>
                <value>
                    <fullName>Declined (Activation)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Activation)</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Activated (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Admin)</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <fields>
        <fullName>Override_PI_Referral_Status__c</fullName>
        <label>Override PI Referral Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Deactivated (Admin)</fullName>
                </value>
                <value>
                    <fullName>Invitation Sent</fullName>
                </value>
                <value>
                    <fullName>Non-Responsive (Admin)</fullName>
                </value>
                <value>
                    <fullName>Declined (Acceptance)</fullName>
                </value>
                <value>
                    <fullName>Accepted (Admin)</fullName>
                </value>
                <value>
                    <fullName>On Hold (Admin)</fullName>
                </value>
                <value>
                    <fullName>Active</fullName>
                    <isActive>false</isActive>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Active (Admin)</fullName>
                    <isActive>false</isActive>
                    <label>Active (Admin)</label>
                </value>
                <value>
                    <fullName>No Response</fullName>
                    <isActive>false</isActive>
                    <label>No Response</label>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                    <isActive>false</isActive>
                    <label>Rejected</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Site__c</fullName>
        <label>Site</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Study Sites</relationshipLabel>
        <relationshipName>Study_Sites</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MyStudySitesController.cls
/**
 * Created by D.Yasinskyi on 22.03.2018
 */
public without sharing class MyStudySitesController {

    @AuraEnabled
    public static String getStudySiteDetail(String trialId) {
        MyStudySitesController.StudySiteDetail studySiteDetail = new MyStudySitesController.StudySiteDetail();
        List<HCP_Enrollment__c> enrollments = new List<HCP_Enrollment__c>();
        try {
            enrollments = HCPEnrollmentService.getEnrollmentsForHCPOnStudySite(trialId);
            studySiteDetail = setStudySiteDetail(enrollments);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + e.getStackTraceString());
        }
        return JSON.serialize(studySiteDetail);
    }

    private static List<Study_Site__c> getStudySites(Set<Id> ids) {
        return [
                SELECT Id,
                        Name,
                        Override_PI_Referral_Status__c,
                        Site__c, Site__r.Name,
                        Site__r.BillingStreet,
                        Site__r.BillingState,
                        Site__r.BillingPostalCode,
                        Site__r.BillingCity,
                        Site__r.Phone
                FROM Study_Site__c
                WHERE Id IN :ids
        ];
    }

    private static MyStudySitesController.StudySiteDetail setStudySiteDetail(List<HCP_Enrollment__c> enrollments) {
        MyStudySitesController.StudySiteDetail studySiteDetail = new MyStudySitesController.StudySiteDetail();
        Map<Id, List<HCPEWrapper>> studySiteEnrolmentMap = new Map<Id, List<HCPEWrapper>>();
        //HCP_Enrollments groups
        Integer pending = 0, activated = 0, onHold = 0, deactivated = 0, declined = 0;

        for (HCP_Enrollment__c enroll : enrollments) {

            if (!studySiteEnrolmentMap.containsKey(enroll.Study_Site__c)) {
                studySiteEnrolmentMap.put(enroll.Study_Site__c, new List<HCPEWrapper>());
            }
            HCPEWrapper enrollWrapper = new HCPEWrapper();
            enrollWrapper.enrollment = enroll;
            enrollWrapper.statusLabel = TranslateHelper.getPickListLabel(HCP_Enrollment__c.Status__c, enroll.Status__c);
            studySiteEnrolmentMap.get(enroll.Study_Site__c).add(enrollWrapper);

            String status = enroll.Status__c;

            if (status == HCPEnrollmentService.HCP_S_ACTIVATED || status == HCPEnrollmentService.HCP_S_ACTIVATED_A){
                activated++;
            } else if(status == HCPEnrollmentService.HCP_S_DEACTIVATED_A) {
                deactivated++;
            } else if(status.contains('On Hold')) {
                onHold++;
            } else if(status.contains('Declined') || status == HCPEnrollmentService.HCP_S_NON_RESPONCIVE_A) {
                declined++;
            } else if (status.contains('Pending')) {
                pending++;
            }
        }

        //set filter info and summaries
        studySiteDetail.filterInfo = new FilterPillInfo(pending, Label.PG_MSS_L_Pending_approval_pending_activation);
        studySiteDetail.summrayContainers.add(new SummaryContainer(Label.PG_MSS_L_Study_sites_overall, String.valueOf(studySiteEnrolmentMap.keySet().size())));
        SummaryContainer PIOverall = new SummaryContainer(Label.PG_MSS_L_Principal_investigators_overall, String.valueOf(enrollments.size()));
        PIOverall.items.add(new LabelValueItem(Label.PG_MSS_L_Activations, String.valueOf(activated)));
        PIOverall.items.add(new LabelValueItem(Label.PG_MSS_L_On_hold, String.valueOf(onHold)));
        PIOverall.items.add(new LabelValueItem(Label.PG_MSS_L_Deactivation, String.valueOf(deactivated)));
        PIOverall.items.add(new LabelValueItem(Label.PG_MSS_L_Decline, String.valueOf(declined)));
        studySiteDetail.summrayContainers.add(PIOverall);

        //set sorted enrollments
        for (Study_Site__c studySite : getStudySites(studySiteEnrolmentMap.keySet())) {

            MyStudySitesController.StudySiteWrapper newWrapper = new MyStudySitesController.StudySiteWrapper();
            newWrapper.studySite = studySite;
            newWrapper.enrollments = studySiteEnrolmentMap.get(studySite.Id);
            studySiteDetail.studySitesDetail.add(newWrapper);
        }

        return studySiteDetail;
    }

    public class StudySiteDetail {
        List<MyStudySitesController.StudySiteWrapper> studySitesDetail;
        List<SummaryContainer> summrayContainers;
        FilterPillInfo filterInfo;

        public StudySiteDetail() {
            studySitesDetail = new List<MyStudySitesController.StudySiteWrapper>();
            summrayContainers = new List<SummaryContainer>();
        }
    }

    public class StudySiteWrapper {
        Study_Site__c studySite;
        List<HCPEWrapper> enrollments;
    }
    public class HCPEWrapper {
        String statusLabel;
        HCP_Enrollment__c enrollment;
    }
}