objects/HCP_Enrollment__c.object
<CustomObject>
    <description>HCP Enrollment</description>
    <fields>
        <fullName>Study_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Hospital of rainbow</description>
        <label>Study Site</label>
        <referenceTo>Study_Site__c</referenceTo>
        <relationshipLabel>Referring HCPs</relationshipLabel>
        <relationshipName>HCP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCP Enrollment</label>
    <nameField>
        <displayFormat>HCPE-{000000}</displayFormat>
        <label>HCP Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCP Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Study_Site__c.object
<CustomObject>
    <description>Study Site Profile</description>
    <label>Study Site</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Study Site Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study Sites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NoTanksModalController.cls
/**
 * Created by D.Yasinskyi on 29.03.2018
 */
public without sharing class NoTanksModalController {

    @AuraEnabled
    public static void deactivateTrial(Id trialId, String userMode) {
        try{
            if (userMode == CommunityService.USER_MODE_HCP) {
                deactivateHCPEnrollment(trialId, userMode);
            } else if (userMode == CommunityService.USER_MODE_PI) {
                deactivateStudySite(trialId, userMode);
            }
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

    private static void deactivateHCPEnrollment(Id trialId, String userMode) {
        HCP_Enrollment__c hcpEnrollment = HCPEnrollmentService.getHCPEnrollmentForHCPByTrial(trialId);
        HCPEnrollmentService.changeStatus(hcpEnrollment.Id, userMode, StudyActions.ACT_HCP_DECLINE);
    }

    private static void deactivateStudySite(Id trialId, String userMode) {
        List<Study_Site__c> studySites = StudySiteService.getStudySiteForPIByTrialId(trialId);
        if(studySites.isEmpty()) throw new AuraHandledException('incorrect Data');
        StudySiteService.changeStatus(studySites[0].Id, userMode, 'decline');
    }
}