objects/Integration_Log__c.object
<CustomObject>
    <fields>
        <fullName>Attempt__c</fullName>
        <label>Attempt</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Call_Duration_Seconds__c</fullName>
        <label>Call Duration Seconds</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>End_Point_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Point URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Status_Code__c</fullName>
        <label>Response Status Code</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Time__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Response</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Source_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Source Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <label>Timeout</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{00000000}</displayFormat>
        <label>Integration Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                </value>
                <value>
                    <fullName>AD</fullName>
                </value>
                <value>
                    <fullName>AE</fullName>
                </value>
                <value>
                    <fullName>AF</fullName>
                </value>
                <value>
                    <fullName>AG</fullName>
                </value>
                <value>
                    <fullName>AI</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
                <value>
                    <fullName>AQ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AT</fullName>
                </value>
                <value>
                    <fullName>AU</fullName>
                </value>
                <value>
                    <fullName>AW</fullName>
                </value>
                <value>
                    <fullName>AX</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BA</fullName>
                </value>
                <value>
                    <fullName>BB</fullName>
                </value>
                <value>
                    <fullName>BD</fullName>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>BF</fullName>
                </value>
                <value>
                    <fullName>BG</fullName>
                </value>
                <value>
                    <fullName>BH</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BJ</fullName>
                </value>
                <value>
                    <fullName>BL</fullName>
                </value>
                <value>
                    <fullName>BM</fullName>
                </value>
                <value>
                    <fullName>BN</fullName>
                </value>
                <value>
                    <fullName>BO</fullName>
                </value>
                <value>
                    <fullName>BQ</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>United States</fullName>
                    <default>true</default>
                    <label>United States</label>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>United Arab Emirates</fullName>
                </value>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Anguilla</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antarctica</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Aruba</fullName>
                </value>
                <value>
                    <fullName>Aland Islands</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Saint Barthélemy</fullName>
                </value>
                <value>
                    <fullName>Bermuda</fullName>
                </value>
                <value>
                    <fullName>Brunei Darussalam</fullName>
                </value>
                <value>
                    <fullName>Bolivia, Plurinational State of</fullName>
                </value>
                <value>
                    <fullName>Bonaire, Sint Eustatius and Saba</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Participant&apos;s First Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s First Name</inlineHelpText>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Participant&apos;s Last Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s Last Name</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mailing City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mailing Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mailing Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mailing State Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Mailing State</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mailing Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Postal_Code__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Mailing Zip/Postal Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Hub_Log__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study Hub Log</label>
        <referenceTo>Integration_Log__c</referenceTo>
        <relationshipLabel>Study_Hub Integration Enrollments</relationshipLabel>
        <relationshipName>Study_Hub_Integration_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IntegrationService.cls
/**
 * Created by Leonid Bartenev
 */

public without sharing class  IntegrationService {
    
    public class IntegrationServiceException extends Exception{}
    
    public class IntegrationMessage{
        public String protocolId;
        public String rrid;
        public SubjectDetails subjectDetails;
        public ReferralDetails referralDetails;
        public AuditLog auditLog;
    }
    
    public class CommunicationPreferences {
        public String Language;
    }
    
    public class Address {
        public String Street;
        public String Street2;
        public String City;
        public String State;
        public String PostalCode;
        public String Country;
        public String CountryCode;
    }
    
    public class ReferralDetails {
        public String ReferralId;
        public Date ReferralDate;
        public Date AcceptedDate;
    }
    
    public class SubjectDetails {
        public String FirstName;
        public String LastName;
        public Address Address;
        public Contact Contact;
    }
    
    public class AuditLog {
        public String UserId;
        public Datetime Timestamp;
    }
    
    public class Contact {
        public String Email;
        public String Phone;
        public CommunicationPreferences CommunicationPreferences;
    }
    
    public class ResponseResult{
        public Integration_Log__c log;
        public HttpResponse httpResponse;
    
        public ResponseResult(HttpResponse httpResponse, Integration_Log__c log){
            this.httpResponse = httpResponse;
            this.log = log;
        }
    }
    
    public static final String END_POINT_URL = 'callout:ServiceNowAndStudyHub';
    public static final Integer TIMEOUT = 120000;
    
    @Future(Callout=true)
    public static void sendPEToServiceNowAsync(Id participantEnrollmentId){
        sendPEToServiceNow(participantEnrollmentId);
    }
    
    public static void sendPEToServiceNow(Id participantEnrollmentId){
        IntegrationMessage integrationMessage = createIntegrationMessage(participantEnrollmentId, false);
        if(integrationMessage == null) return;
        ResponseResult result = sendIntegrationMessage(participantEnrollmentId, integrationMessage);
        update new Participant_Enrollment__c(
                Id = participantEnrollmentId
                //Service_Now_Sent_Date__c = Datetime.now()
                //Study_Hub_Log__c = result.log.Id
        );
    }
    
    @Future(Callout=true)
    public static void sendPEToStudyHubAsync(Id participantEnrollmentId){
        sendPEToStudyHub(participantEnrollmentId);
    }
    
    public static void sendPEToStudyHub(Id participantEnrollmentId){
        IntegrationMessage integrationMessage = createIntegrationMessage(participantEnrollmentId, true);
        System.debug('PE: ' + integrationMessage);
        if(integrationMessage == null) return;
        ResponseResult result = sendIntegrationMessage(participantEnrollmentId, integrationMessage);
        update new Participant_Enrollment__c(
                Id = participantEnrollmentId,
                Study_Hub_Log__c = result.log.Id
        );
    }
    
    public static ResponseResult sendIntegrationMessage(String sourceId, IntegrationMessage integrationMessage){
        String dataJSON = JSON.serializePretty(integrationMessage, true);
        ResponseResult responseResult;
        Integer currentAttempt = 1;
        Integer attemptsCount = 3;
        List<Integration_Log__c> logs = new List<Integration_Log__c>();
        while(true){
            responseResult = send(END_POINT_URL, 'POST', TIMEOUT, sourceId, dataJSON, currentAttempt);
            logs.add(responseResult.log);
            if((responseResult.httpResponse != null && responseResult.httpResponse.getStatusCode() == 500) && currentAttempt < attemptsCount){
                currentAttempt ++;
                sleep(10000);
                continue;
            }
            break;
        }
        insert logs;
        return responseResult;
    }
    
    public static ResponseResult send(String url, String method, Integer timeout,String sourceId, String requestBody, Integer attemptNumber){
        //init request:
        HttpRequest request = new HttpRequest();
        request.setEndpoint(url);
        request.setHeader('Content-Type', 'application/json');
        request.setMethod('POST');
        request.setTimeout(timeout);
        request.setBody(requestBody);
        Datetime requestDT = Datetime.now();
        Datetime responseDT;
        //init log:
        Integration_Log__c log = new Integration_Log__c(
                End_Point_URL__c = url.mid(0, 255),
                Method__c = method,
                Request__c = requestBody.mid(0, 32768),
                Response_Time__c = requestDT,
                Source_Id__c = sourceId.mid(0, 255),
                Attempt__c = attemptNumber,
                Request_Time__c = requestDT,
                Timeout__c = timeout
        );
        Http h = new Http();
        //send request:
        HttpResponse response;
        try{
            response = h.send(request);
            responseDT = Datetime.now();
            System.debug('RESPONSE: ' + response.getStatus() + ' code: ' + response.getStatusCode());
            //update log:
            log.Response_Status__c = response.getStatus();
            log.Response_Status_Code__c = response.getStatusCode();
            log.Response__c = response.getBody().mid(0, 32768);
        }catch (Exception e){
            responseDT = Datetime.now();
            System.debug('ERROR: ' + e.getMessage());
            //update log:
            log.Exception__c = (e.getMessage() + '\n' + e.getStackTraceString()).mid(0, 32768);
        }finally {
            //update log:
            log.Response_Time__c = responseDT;
            log.Call_Duration_Seconds__c = (responseDT.getTime() - requestDT.getTime()) / 1000.0;
        }
        return new ResponseResult(response, log);
    }
    
    public static IntegrationMessage createIntegrationMessage(Id participantEnrollmentId, Boolean setAcceptedDate){
        Participant_Enrollment__c pe = [
                SELECT Id,
                        Name,
                        Participant__r.First_Name__c,
                        Participant__r.Last_Name__c,
                        Participant__r.Phone__c,
                        Participant__r.Email__c,
                        Participant__r.Mailing_City__c,
                        Participant__r.Mailing_State__c,
                        Participant__r.Mailing_State_Code__c,
                        Participant__r.Mailing_Zip_Postal_Code__c,
                        Participant__r.Mailing_Country__c,
                        Participant__r.Mailing_Country_Code__c,
                        Participant__r.Country_Code__c,
                        Participant__r.Country__c,
                        Participant__r.Mailing_Street__c,
                        Participant__r.Language_Preference_Code__c,
                        Referral_ID__c,
                        Referred_Date__c,
                        Study_Site__r.Protocol_ID__c,
                        Study_Site__r.Is_Virtual_Study_Site__c
                FROM Participant_Enrollment__c
                WHERE Id =: participantEnrollmentId
        ];
        
        if(!pe.Study_Site__r.Is_Virtual_Study_Site__c) return null;
        
        Address addr = new Address();
        addr.Street = pe.Participant__r.Mailing_Street__c;
        addr.Street2 = pe.Participant__r.Mailing_Street__c;
        addr.City = pe.Participant__r.Mailing_City__c;
        addr.State = pe.Participant__r.Mailing_State_Code__c;
        addr.PostalCode = pe.Participant__r.Mailing_Zip_Postal_Code__c;
        addr.Country = pe.Participant__r.Mailing_Country__c;
        addr.CountryCode = pe.Participant__r.Mailing_Country_Code__c;
        
        CommunicationPreferences communicationPreferences = new CommunicationPreferences();
        communicationPreferences.Language = pe.Participant__r.Language_Preference_Code__c;
        
        Contact contact = new Contact();
        contact.Email = pe.Participant__r.Email__c;
        contact.Phone = pe.Participant__r.Phone__c;
        contact.CommunicationPreferences = communicationPreferences;
        
        ReferralDetails referralDetails = new ReferralDetails();
        referralDetails.ReferralId = pe.Name;
        referralDetails.ReferralDate =  pe.Referred_Date__c;
        if(setAcceptedDate) referralDetails.AcceptedDate = Date.today();
        
        SubjectDetails subjectDetails = new SubjectDetails();
        subjectDetails.FirstName = pe.Participant__r.First_Name__c;
        subjectDetails.LastName = pe.Participant__r.Last_Name__c;
        subjectDetails.Address = addr;
        subjectDetails.Contact = contact; 
    
        AuditLog auditLog = new AuditLog();
        auditLog.UserId = UserInfo.getUserId();
        auditLog.Timestamp = Datetime.now();
        
        IntegrationMessage integrationMessage = new IntegrationMessage();
        integrationMessage.protocolId = pe.Study_Site__r.Protocol_ID__c;
        integrationMessage.rrid = pe.Id;
        integrationMessage.subjectDetails = subjectDetails;
        integrationMessage.referralDetails = referralDetails;
        integrationMessage.auditLog = auditLog;

        return integrationMessage;
    }
    
    //timeout on milliSeconds
    public static void sleep(Long milliSeconds){
        Long timeDiff = 0;
        Datetime firstTime = System.now();
        do {
            timeDiff = System.now().getTime() - firstTime.getTime();
        } while (timeDiff <= milliSeconds);
    }


}