objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Participant_Enrollment__c.object
<CustomObject>
    <description>Participant Profile</description>
    <fields>
        <fullName>Last_Status_Changed_Notes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Status Changed Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Non_Enrollment_Reason__c</fullName>
        <label>Non-Enrollment Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Participant_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Site No Longer Accepting Referrals</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t Meet Pre-Screening Eligibility</fullName>
                </value>
                <value>
                    <fullName>Declined Practitioner</fullName>
                </value>
                <value>
                    <fullName>PI Decision</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t Show For Initial Visit</fullName>
                </value>
                <value>
                    <fullName>Didn&apos;t Sign Consent</fullName>
                </value>
                <value>
                    <fullName>Failed Inclusion/Exclusion Criteria</fullName>
                </value>
                <value>
                    <fullName>Patient Declined</fullName>
                </value>
                <value>
                    <fullName>Visit Out Of Window</fullName>
                </value>
                <value>
                    <fullName>Patient Decision</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Could not schedule visit</fullName>
                    <isActive>false</isActive>
                    <label>Could not schedule visit</label>
                </value>
                <value>
                    <fullName>Did not respond to contact attempts</fullName>
                    <isActive>false</isActive>
                    <label>Did not respond to contact attempts</label>
                </value>
                <value>
                    <fullName>Failed screening / does not qualify</fullName>
                    <isActive>false</isActive>
                    <label>Failed screening / does not qualify</label>
                </value>
                <value>
                    <fullName>No longer interested</fullName>
                    <isActive>false</isActive>
                    <label>No longer interested</label>
                </value>
                <value>
                    <fullName>No show for scheduled visit</fullName>
                    <isActive>false</isActive>
                    <label>No show for scheduled visit</label>
                </value>
                <value>
                    <fullName>Not eligible</fullName>
                    <isActive>false</isActive>
                    <label>Not eligible</label>
                </value>
                <value>
                    <fullName>Not willing to sign informed consent</fullName>
                    <isActive>false</isActive>
                    <label>Not willing to sign informed consent</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant_Status_Last_Changed_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Participant Status Last Changed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Participant_Status__c</fullName>
        <description>HCP/Physician Participant Participant Status</description>
        <inlineHelpText>HCP/Physician Participant Participant Status</inlineHelpText>
        <label>Participant Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Referral Sent to PI</fullName>
                </value>
                <value>
                    <fullName>Excluded from Referring</fullName>
                </value>
                <value>
                    <fullName>Referral Accepted</fullName>
                </value>
                <value>
                    <fullName>Contact Successful</fullName>
                </value>
                <value>
                    <fullName>Eligibility Passed</fullName>
                </value>
                <value>
                    <fullName>Screening Complete</fullName>
                </value>
                <value>
                    <fullName>Enrollment Success</fullName>
                </value>
                <value>
                    <fullName>Referral On Hold</fullName>
                </value>
                <value>
                    <fullName>Contact Attempt In Progress</fullName>
                </value>
                <value>
                    <fullName>Screening In Progress</fullName>
                </value>
                <value>
                    <fullName>Referral Declined</fullName>
                </value>
                <value>
                    <fullName>Contact Failed</fullName>
                </value>
                <value>
                    <fullName>Eligibility Failed</fullName>
                </value>
                <value>
                    <fullName>Screening Failed</fullName>
                </value>
                <value>
                    <fullName>Enrollment Failed</fullName>
                </value>
                <value>
                    <fullName>Failed Referral</fullName>
                </value>
                <value>
                    <fullName>Failed Review</fullName>
                </value>
                <value>
                    <fullName>Pending Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>Participant__c</referenceTo>
        <relationshipLabel>Participant Enrollments</relationshipLabel>
        <relationshipName>Participant_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant Enrollment</label>
    <nameField>
        <displayFormat>REFERRALID{00000}</displayFormat>
        <label>Participant Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Action_ChangePEStatusByPIRemote.cls
/**
 * Created by Leonid Bartenev
 */

public class Action_ChangePEStatusByPIRemote {
    
    @AuraEnabled
    public static String getReferralDeclineReasons(){
        try {
            List<LabelValueItem> referralDeclineReasons = new List<LabelValueItem>();
            for(String reason : ReferralProfileRemote.REASONS_MAP.get('Referral Declined')){
                referralDeclineReasons.add(new LabelValueItem(TranslateHelper.getPickListLabel(Participant_Enrollment__c.Non_Enrollment_Reason__c,reason), reason));
            }
            return JSON.serialize(referralDeclineReasons);
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static void updatePE(String peId, String status, String reason, String notes){
        Savepoint sp = Database.setSavepoint();
        try{
            Participant_Enrollment__c pe  = [SELECT Id, Participant__c FROM Participant_Enrollment__c WHERE Id =: peId];
            pe.Id = peId;
            pe.Participant_Status_Last_Changed_Date__c = Datetime.now();
            pe.Last_Status_Changed_Notes__c = notes;
            pe.Participant_Status__c = status;
            pe.Non_Enrollment_Reason__c = reason;
            update pe;
        }catch (Exception e){
            Database.rollback(sp);
            throw new AuraHandledException(e.getMessage() + '\n' + e.getStackTraceString());
        }
    }

}