objects/Participant__c.object
<CustomObject>
    <description>Participant</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Participants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Participant&apos;s First Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s First Name</inlineHelpText>
        <label>First Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Participant&apos;s Last Name can be removed from layout for PI compliance purposes</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <inlineHelpText>Participant&apos;s Last Name</inlineHelpText>
        <label>Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RRProfileController.cls
/**
 * Created by D.Yasinskyi on 04.05.2018
 */
public without sharing class RRProfileController {

    @AuraEnabled
    public static String getUser() {

        List<User> currentUser = [
                SELECT Id
                        , Contact.Name
                , SmallPhotoUrl
                FROM User
                WHERE Id = : UserInfo.getUserId()
        ];
        UserWrapper result = new UserWrapper();
        result.user = currentUser[0];
        List<Participant__c> participantForCurrentUser = [
                SELECT  Id,
                        First_Name__c,
                        Last_Name__c
                FROM Participant__c
                WHERE Contact__c = :result.user.ContactId
        ];
        if(!participantForCurrentUser.isEmpty()){
            result.participantName = participantForCurrentUser[0].First_Name__c + ' ' + participantForCurrentUser[0].Last_Name__c;
        }

        return JSON.serialize(result);
    }

    @AuraEnabled
    public static String getLogoutURL() {
        return Site.getBaseUrl();
    }
    public class UserWrapper{
        public User user;
        public String participantName;
    }
}